### PR TITLE
[mpm-dev] Add Hencky strain, refactor Constitutive models

### PR DESCRIPTION
**Pull request by yiminlin-tri**
This change is [Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/23)

### CODE REVIEW

**Review by yiminlin-tri — COMMENTED** [review]
+@xuchenhan-tri Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/23#-:-N5q0PQw2sdZj65Re9bp:b6w1hxi)* status: 0 of 14 files reviewed, all discussions resolved (waiting on @xuchenhan-tri)

**Review by yiminlin-tri — COMMENTED** [review]
> Reviewed 13 of 14 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @xuchenhan-tri)

**Review by xuchen-han — CHANGES_REQUESTED** [review]
Sorry for the delay. I was tied up with another PR. 

Non-test files reviewed. PTAL.

> Reviewed 10 of 14 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/23#-:-N5qunSCEL7uT76rgMv6:bapoet8)* status: all files reviewed, 9 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/ConstitutiveModel.h` line 13 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/23#-N5qpXwW6z44_n5bB40F:-N5qpXwW6z44_n5bB40G:bk0b8r7) ([raw file](https://github.com/yiminlin-tri/drake/blob/05ad4a2d57a731b9d9ddee88779823d20ab123c5/multibody/fem/mpm-dev/ConstitutiveModel.h#L13)):*
> ```objc
> 
> // A base class providing the interface of Constitutive model
> class ConstitutiveModel {
> ```

Let's put each of these classes in individual files.
___
*[`multibody/fem/mpm-dev/ConstitutiveModel.h` line 23 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/23#-N5qpk7e4e2a2lVaZn4g:-N5qpk7e4e2a2lVaZn4h:b-vglbhv) ([raw file](https://github.com/yiminlin-tri/drake/blob/05ad4a2d57a731b9d9ddee88779823d20ab123c5/multibody/fem/mpm-dev/ConstitutiveModel.h#L23)):*
> ```objc
>     // First Piola Kirchhoff stress density: P = dpsi/dF
>     virtual void CalcFirstPiolaKirchhoffStress(
>             const Matrix3<double>& F, EigenPtr<Matrix3<double>> P) const = 0;
> ```

nit, I think it would probably be safe to take Matrix3<double>* instead of EigenPtr<Matrix3<double>> here.
___
*[`multibody/fem/mpm-dev/ConstitutiveModel.cc` line 66 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/23#-N5qr4vKEa2U7m6wUuQy:-N5qqpGlA51t13woXjfz:b-n3lgn9) ([raw file](https://github.com/yiminlin-tri/drake/blob/05ad4a2d57a731b9d9ddee88779823d20ab123c5/multibody/fem/mpm-dev/ConstitutiveModel.cc#L66)):*
> ```cpp
>     double sum_log_sigma = 0.0;
>     for (int d = 0; d < 3; ++d) {
>         sum_log_sigma += log(sigma(d));
> ```

BTW I believe you could do something along the line of `sigma.array().log().sum()`.
___
*[`multibody/fem/mpm-dev/ConstitutiveModel.cc` line 69 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/23#-N5qrIcyDpSJrqAhQYYW:-N5qrIcyDpSJrqAhQYYX:bnl4syh) ([raw file](https://github.com/yiminlin-tri/drake/blob/05ad4a2d57a731b9d9ddee88779823d20ab123c5/multibody/fem/mpm-dev/ConstitutiveModel.cc#L69)):*
> ```cpp
>     }
>     for (int d = 0; d < 3; ++d) {
>         sigma(d) = (2*mu_*log(sigma(d)) + lambda_*sum_log_sigma)/sigma(d);
> ```

Don't take more logs than necessary. We already have the log of the sigmas above. Ditto throughout.

Also, I see that you are trying to save a tiny bit of memory by reusing sigma. Not sure if it's worth it since it's just 3 doubles. But at least document what you are doing here.
___
*[`multibody/fem/mpm-dev/ConstitutiveModel.cc` line 87 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/23#-N5qt1Fy9Nt_07A8ISdY:-N5qt1Fy9Nt_07A8ISdZ:b-6nfl3p) ([raw file](https://github.com/yiminlin-tri/drake/blob/05ad4a2d57a731b9d9ddee88779823d20ab123c5/multibody/fem/mpm-dev/ConstitutiveModel.cc#L87)):*
> ```cpp
>     }
>     for (int d = 0; d < 3; ++d) {
>         sigma(d)  = 2*mu_*log(sigma(d)) + lambda_*sum_log_sigma;
> ```

Since the formula for computing the kirchhoff stress isn't in the paper, we should probably right it down here?
___
*[`multibody/fem/mpm-dev/MPMDriver.h` line 34 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/23#-N5qtZFA-6WOtbBeam-B:-N5qtZFA-6WOtbBeam-C:b-9uf253) ([raw file](https://github.com/yiminlin-tri/drake/blob/05ad4a2d57a731b9d9ddee88779823d20ab123c5/multibody/fem/mpm-dev/MPMDriver.h#L34)):*
> ```objc
>     struct MaterialParameters {
>         // Constitutive model of the object
>         std::shared_ptr<ConstitutiveModel> constitutive_model;
> ```

It's rarely a good idea to use shared pointers...
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 125 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/23#-N5qtqsn06OlcNMF2HB-:-N5qtqsn06OlcNMF2HB0:bpv0eml) ([raw file](https://github.com/yiminlin-tri/drake/blob/05ad4a2d57a731b9d9ddee88779823d20ab123c5/multibody/fem/mpm-dev/MPMDriver.cc#L125)):*
> ```cpp
>         particles_.AddParticle(xp, vp, init_m, reference_volume_p,
>                                deformation_grad_p, kirchhoff_stress_p,
>                                B_p, m_param.constitutive_model);
> ```

I think we'd want to make copy of the constitutive model for each particle.
___
*[`multibody/fem/mpm-dev/main.cpp` line 91 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/23#-N5qu-_cADxNRGCefwgl:-N5qu-_cADxNRGCefwgm:b-nk3ivx) ([raw file](https://github.com/yiminlin-tri/drake/blob/05ad4a2d57a731b9d9ddee88779823d20ab123c5/multibody/fem/mpm-dev/main.cpp#L91)):*
> ```cpp
>     velocity_sphere.rotational() = Vector3<double>{0.0, 0.0, 0.0};
>     std::shared_ptr<SaintVenantKirchhoffWithHenckyModel> constitutive_model
>             = std::make_shared<SaintVenantKirchhoffWithHenckyModel>(8e4, 0.4);
> ```

shared_ptr bad!
___
*[`multibody/fem/mpm-dev/Particles.h` line 58 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/23#-N5quPLy-F4g6ZFjbS4e:-N5quPLy-F4g6ZFjbS4f:bz2hs8f) ([raw file](https://github.com/yiminlin-tri/drake/blob/05ad4a2d57a731b9d9ddee88779823d20ab123c5/multibody/fem/mpm-dev/Particles.h#L58)):*
> ```objc
>     void set_B_matrix(int index, const Matrix3<double>& B_matrix);
>     void set_constitutive_model(int index,
>                         std::shared_ptr<ConstitutiveModel> constitutive_model);
> ```

It's better to use a unique_ptr here.
___
*[`multibody/fem/mpm-dev/Particles.h` line 90 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/23#-N5quUu40dMa9C_lztmb:-N5quUu40dMa9C_lztmc:bz2hs8f) ([raw file](https://github.com/yiminlin-tri/drake/blob/05ad4a2d57a731b9d9ddee88779823d20ab123c5/multibody/fem/mpm-dev/Particles.h#L90)):*
> ```objc
>                      const Matrix3<double>& kirchhoff_stress,
>                      const Matrix3<double>& B_matrix,
>                      std::shared_ptr<ConstitutiveModel> constitutive_model);
> ```

It's better to use a unique_ptr here.

**Review by yiminlin-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/23)* status: all files reviewed, 8 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/ConstitutiveModel.h` line 13 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/23#-N5qpXwW6z44_n5bB40F:-N6JP6W9E2mDdDPemJQ6:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/05ad4a2d57a731b9d9ddee88779823d20ab123c5/multibody/fem/mpm-dev/ConstitutiveModel.h#L13)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Let's put each of these classes in individual files.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/ConstitutiveModel.cc` line 69 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/23#-N5qrIcyDpSJrqAhQYYW:-N6JTZy90x5uaM5gCElv:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/05ad4a2d57a731b9d9ddee88779823d20ab123c5/multibody/fem/mpm-dev/ConstitutiveModel.cc#L69)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Don't take more logs than necessary. We already have the log of the sigmas above. Ditto throughout.

Also, I see that you are trying to save a tiny bit of memory by reusing sigma. Not sure if it's worth it since it's just 3 doubles. But at least document what you are doing here.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/ConstitutiveModel.cc` line 87 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/23#-N5qt1Fy9Nt_07A8ISdY:-N6JT_GR9z_5k31BXehw:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/05ad4a2d57a731b9d9ddee88779823d20ab123c5/multibody/fem/mpm-dev/ConstitutiveModel.cc#L87)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Since the formula for computing the kirchhoff stress isn't in the paper, we should probably right it down here?
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/MPMDriver.h` line 34 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/23#-N5qtZFA-6WOtbBeam-B:-N6JPDCc3i3wEfuHbm5r:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/05ad4a2d57a731b9d9ddee88779823d20ab123c5/multibody/fem/mpm-dev/MPMDriver.h#L34)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

It's rarely a good idea to use shared pointers...
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 125 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/23#-N5qtqsn06OlcNMF2HB-:-N6JPF1Z6vfKfanY7M38:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/05ad4a2d57a731b9d9ddee88779823d20ab123c5/multibody/fem/mpm-dev/MPMDriver.cc#L125)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I think we'd want to make copy of the constitutive model for each particle.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/main.cpp` line 91 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/23#-N5qu-_cADxNRGCefwgl:-N6JPNo4DpfUZxw0NA-g:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/05ad4a2d57a731b9d9ddee88779823d20ab123c5/multibody/fem/mpm-dev/main.cpp#L91)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

shared_ptr bad!
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/Particles.h` line 58 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/23#-N5quPLy-F4g6ZFjbS4e:-N6JPWHbEEyMI8n__q82:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/05ad4a2d57a731b9d9ddee88779823d20ab123c5/multibody/fem/mpm-dev/Particles.h#L58)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

It's better to use a unique_ptr here.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/Particles.h` line 90 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/23#-N5quUu40dMa9C_lztmb:-N6JPWoh6byn8qM-J2Sv:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/05ad4a2d57a731b9d9ddee88779823d20ab123c5/multibody/fem/mpm-dev/Particles.h#L90)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

It's better to use a unique_ptr here.
</blockquote></details>

Done.

**Review by xuchen-han — APPROVED** [review]
:lgtm: with a couple of remaining nits.

> Reviewed 15 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/23#-:-N6JXt4n5JXIu3cQHD8P:bwgpt2v)* status: all files reviewed, 4 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/ConstitutiveModel.h` line 3 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/23#-N6JUXwv4fL-AiwLDCRL:-N6JUXwv4fL-AiwLDCRM:bav6isg) ([raw file](https://github.com/yiminlin-tri/drake/blob/ada32a800fe2ba1bc834ef02cf7b3818086aa0bb/multibody/fem/mpm-dev/ConstitutiveModel.h#L3)):*
> ```objc
> #pragma once
> 
> #include <iostream>
> ```

nit not needed.
___
*[`multibody/fem/mpm-dev/CorotatedModel.h` line 3 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/23#-N6JVI__1FcBmwV2Ycb1:-N6JVI__1FcBmwV2Ycb2:b1mrxo) ([raw file](https://github.com/yiminlin-tri/drake/blob/ada32a800fe2ba1bc834ef02cf7b3818086aa0bb/multibody/fem/mpm-dev/CorotatedModel.h#L3)):*
> ```objc
> #pragma once
> 
> #include <iostream>
> ```

nit unused.
___
*[`multibody/fem/mpm-dev/SaintVenantKirchhoffWithHenckyModel.cc` line 20 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/23#-N6JW7-Q17_iaHk2VTLG:-N6JW7-Q17_iaHk2VTLH:b-uqafaa) ([raw file](https://github.com/yiminlin-tri/drake/blob/ada32a800fe2ba1bc834ef02cf7b3818086aa0bb/multibody/fem/mpm-dev/SaintVenantKirchhoffWithHenckyModel.cc#L20)):*
> ```cpp
>     const Matrix3<double>& U  = svd.matrixU();
>     const Matrix3<double>& V  = svd.matrixV();
>     VectorX<double> sigma     = svd.singularValues();
> ```

nit, ditto for function below



_Suggestion:_
```cpp
    Vector3<double> sigma     = svd.singularValues();
```
___
*[`multibody/fem/mpm-dev/SaintVenantKirchhoffWithHenckyModel.cc` line 22 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/23#-N6JWDG22Bup7Z7xV2bC:-N6JWDG22Bup7Z7xV2bD:b-uqafaa) ([raw file](https://github.com/yiminlin-tri/drake/blob/ada32a800fe2ba1bc834ef02cf7b3818086aa0bb/multibody/fem/mpm-dev/SaintVenantKirchhoffWithHenckyModel.cc#L22)):*
> ```cpp
>     VectorX<double> sigma     = svd.singularValues();
>     // logs of singular values
>     VectorX<double> log_sigma = sigma.array().log();
> ```

nit, ditto for function below



_Suggestion:_
```cpp
    Vector3<double> log_sigma = sigma.array().log();
```

**Review by yiminlin-tri — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/23#-:-N6JnWBkA0Ni8ZOadYXF:b-ucfknh)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)

**Review by xuchen-han — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)

**Pull request merged**
