### PR TITLE
CorotatedModel Class

### PR DESCRIPTION
**Pull request by yiminlin-tri**
A class implementing the fixed corotated model (constitutive model) that relates deformation gradient F with stress P and tau.

---
This change is [Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/8)

### CODE REVIEW

**Review by yiminlin-tri — COMMENTED** [review]
@xuchenhan-tri Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/8#-:-N2n2wsN1ruzgLuO3Toh:b7am51h)* status: 0 of 4 files reviewed, all discussions resolved

**Review by xuchen-han — CHANGES_REQUESTED** [review]
:lgtm:  with a A few comments. PTAL.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/8#-:-N2n6ECU04PvWhaPl5rP:b2e5xe2)* status: all files reviewed, 6 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/CorotatedModel.h` line 10 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/8#-N2n4GziAltcFJloVXT5:-N2n4GziAltcFJloVXT6:b425a3x) ([raw file](https://github.com/yiminlin-tri/drake/blob/db1d4c3db05915bd05695019529b20e9dc2959f7/multibody/fem/mpm-dev/CorotatedModel.h#L10)):*
> ```objc
> namespace mpm {
> 
> // A implementation of 3D quadratic B spline
> ```

Copypaste error.
___
*[`multibody/fem/mpm-dev/CorotatedModel.h` line 13 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/8#-N2n40w73Imd8YCPQShR:-N2n40w73Imd8YCPQShS:b-85b3fr) ([raw file](https://github.com/yiminlin-tri/drake/blob/db1d4c3db05915bd05695019529b20e9dc2959f7/multibody/fem/mpm-dev/CorotatedModel.h#L13)):*
> ```objc
> class CorotatedModel {
>  public:
>     // Default material: Young's modulus 2.0, Poisson's ratio 0.0
> ```

A default E=2.0 doesn't seem reasonable (way too low). Consider either removing the default constructor to force the user to initialize.
___
*[`multibody/fem/mpm-dev/CorotatedModel.h` line 16 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/8#-N2n4oGSEp6hR2Gc6cOU:-N2n4oGSEp6hR2Gc6cOV:bvm9i59) ([raw file](https://github.com/yiminlin-tri/drake/blob/db1d4c3db05915bd05695019529b20e9dc2959f7/multibody/fem/mpm-dev/CorotatedModel.h#L16)):*
> ```objc
>     CorotatedModel();
>     // Constructor uses Young's modulus E and Poisson's ratio nu
>     CorotatedModel(const double E, const double nu);
> ```

FYI, the const here doesn't do anything since the parameters are passed by value.
___
*[`multibody/fem/mpm-dev/CorotatedModel.h` line 18 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/8#-N2n60_h6GSz9AVL1yvM:-N2n60_h6GSz9AVL1yvN:be0f0nh) ([raw file](https://github.com/yiminlin-tri/drake/blob/db1d4c3db05915bd05695019529b20e9dc2959f7/multibody/fem/mpm-dev/CorotatedModel.h#L18)):*
> ```objc
>     CorotatedModel(const double E, const double nu);
> 
>     // First Piola Kirchhoff stress: P = dpsi/dF
> ```

nit, technically, these are the stress densities instead of actual stresses.
___
*[`multibody/fem/mpm-dev/CorotatedModel.h` line 25 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/8#-N2n4yCL2j8q6wFvTZY5:-N2n4yCMBzZX7WTbYXCm:bhzwvv1) ([raw file](https://github.com/yiminlin-tri/drake/blob/db1d4c3db05915bd05695019529b20e9dc2959f7/multibody/fem/mpm-dev/CorotatedModel.h#L25)):*
> ```objc
>     void CalcKirchhoffStress(const Matrix3<double>& F,
>                              EigenPtr<Matrix3<double>> tau);
>     // First Piola Kirchhoff stress: P = dpsi/dF
> ```

copypaste error.
___
*[`multibody/fem/mpm-dev/CorotatedModel.cc` line 12 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/8#-N2n4aUX6v3R7o3L8TVG:-N2n4aUX6v3R7o3L8TVH:b-ijouci) ([raw file](https://github.com/yiminlin-tri/drake/blob/db1d4c3db05915bd05695019529b20e9dc2959f7/multibody/fem/mpm-dev/CorotatedModel.cc#L12)):*
> ```cpp
>     mu_(E/(2*(1+nu))), lambda_(E*nu/(1+nu)/(1-2*nu)) {
>         DRAKE_ASSERT(E >= 0);
>         DRAKE_ASSERT(nu >= 0.0 && nu <= 0.5);
> ```

The valid range of nu is (-1.0, 0.5), noninclusive, otherwise we'd have a divide by zero two lines above.
___
*[`multibody/fem/mpm-dev/test/CorotatedModel_test.cc` line 29 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/8#-N2n5pza8au7WUQZ5Lcn:-N2n5pza8au7WUQZ5Lco:b-9uxtym) ([raw file](https://github.com/yiminlin-tri/drake/blob/db1d4c3db05915bd05695019529b20e9dc2959f7/multibody/fem/mpm-dev/test/CorotatedModel_test.cc#L29)):*
> ```cpp
>             1, 4, 1,
>             2, 1, 5).finished();
>     const Matrix3<double> P_exact1 = (Matrix3<double>() <<
> ```

It's hard to eyeball whether the stress is correct. Could we add a sanity check that when F is a rotation matrix, both stress measures are zero.

**Review by yiminlin-tri — COMMENTED** [review]
Fixed. Thanks! 

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/8#-:-N2nARk2CkS-sSKm3gf9:bi986cp)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/CorotatedModel.h` line 10 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/8#-N2n4GziAltcFJloVXT5:-N2n78uU3sQzUMoYin2t:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/db1d4c3db05915bd05695019529b20e9dc2959f7/multibody/fem/mpm-dev/CorotatedModel.h#L10)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Copypaste error.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/CorotatedModel.h` line 13 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/8#-N2n40w73Imd8YCPQShR:-N2n7XxqCP_yz4esk-u2:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/db1d4c3db05915bd05695019529b20e9dc2959f7/multibody/fem/mpm-dev/CorotatedModel.h#L13)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

A default E=2.0 doesn't seem reasonable (way too low). Consider either removing the default constructor to force the user to initialize.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/CorotatedModel.h` line 16 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/8#-N2n4oGSEp6hR2Gc6cOU:-N2n83z50JEQ9psvZtSp:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/db1d4c3db05915bd05695019529b20e9dc2959f7/multibody/fem/mpm-dev/CorotatedModel.h#L16)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

FYI, the const here doesn't do anything since the parameters are passed by value.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/CorotatedModel.h` line 18 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/8#-N2n60_h6GSz9AVL1yvM:-N2n9xLS7-6TyNvWbbH7:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/db1d4c3db05915bd05695019529b20e9dc2959f7/multibody/fem/mpm-dev/CorotatedModel.h#L18)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, technically, these are the stress densities instead of actual stresses.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/CorotatedModel.h` line 25 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/8#-N2n4yCL2j8q6wFvTZY5:-N2n8IwG5rh0aFWrkG-d:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/db1d4c3db05915bd05695019529b20e9dc2959f7/multibody/fem/mpm-dev/CorotatedModel.h#L25)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

copypaste error.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/CorotatedModel.cc` line 12 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/8#-N2n4aUX6v3R7o3L8TVG:-N2n7op842zEPHZPhUB7:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/db1d4c3db05915bd05695019529b20e9dc2959f7/multibody/fem/mpm-dev/CorotatedModel.cc#L12)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The valid range of nu is (-1.0, 0.5), noninclusive, otherwise we'd have a divide by zero two lines above.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/CorotatedModel_test.cc` line 29 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/8#-N2n5pza8au7WUQZ5Lcn:-N2n9poF0M6bUdt16cuR:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/db1d4c3db05915bd05695019529b20e9dc2959f7/multibody/fem/mpm-dev/test/CorotatedModel_test.cc#L29)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

It's hard to eyeball whether the stress is correct. Could we add a sanity check that when F is a rotation matrix, both stress measures are zero.
</blockquote></details>

Done

**Review by xuchen-han — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/CorotatedModel.h` line 18 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/8#-N2n60_h6GSz9AVL1yvM:-N2nDwiVBy-bGibUQrQM:b-d75w1e) ([raw file](https://github.com/yiminlin-tri/drake/blob/db1d4c3db05915bd05695019529b20e9dc2959f7/multibody/fem/mpm-dev/CorotatedModel.h#L18)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Done
</blockquote></details>

same for kirchhoff stress.
___
*[`multibody/fem/mpm-dev/CorotatedModel.cc` line 12 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/8#-N2n4aUX6v3R7o3L8TVG:-N2nE2PwEd_TAe_DgQ1b:b4xbpg9) ([raw file](https://github.com/yiminlin-tri/drake/blob/db1d4c3db05915bd05695019529b20e9dc2959f7/multibody/fem/mpm-dev/CorotatedModel.cc#L12)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Done
</blockquote></details>

There's actually nothing wrong with negative nu (as long as it's > -1.0). It's unusual, but there are materials like that.

**Review by yiminlin-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/8)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/CorotatedModel.h` line 18 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/8#-N2n60_h6GSz9AVL1yvM:-N2nEfVxCeEPo9d_Hrju:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/db1d4c3db05915bd05695019529b20e9dc2959f7/multibody/fem/mpm-dev/CorotatedModel.h#L18)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

same for kirchhoff stress.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/CorotatedModel.cc` line 12 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/8#-N2n4aUX6v3R7o3L8TVG:-N2nEimG3BPw1lMIWN3R:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/db1d4c3db05915bd05695019529b20e9dc2959f7/multibody/fem/mpm-dev/CorotatedModel.cc#L12)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

There's actually nothing wrong with negative nu (as long as it's > -1.0). It's unusual, but there are materials like that.
</blockquote></details>

Done

**Review by xuchen-han — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)

**Pull request merged**
