### PR TITLE
Add gradient evaluation to BSpline

### PR DESCRIPTION
**Pull request by yiminlin-tri**
This change is [Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/7)

### CODE REVIEW

**Review by yiminlin-tri — COMMENTED** [review]
@xuchenhan-tri   Just put it out there before I leave the office. Don't feel pressured reviewing it. Have a nice weekend! :smile: 

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/7#-:-N2UBPjt2QhMPXUjBzHJ:bp675z1)* status: 0 of 3 files reviewed, all discussions resolved

**Review by xuchen-han — CHANGES_REQUESTED** [review]
A few comments. PTAL.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/7#-:-N2lnsW38Exg6LVyOfK-:b-hvscer)* status: all files reviewed, 2 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/BSpline.cc` line 35 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/7#-N2ln-o-1DDBUpCDpu62:-N2ln-o-1DDBUpCDpu63:b-pcqtg8) ([raw file](https://github.com/yiminlin-tri/drake/blob/f8cd27cbf0bf77600f149976e361a6b01102ad20/multibody/fem/mpm-dev/BSpline.cc#L35)):*
> ```cpp
> }
> 
> Vector3<double> BSpline::EvalGradientBasis(const Vector3<double>& x) {
> ```

BTW, there are some repeated calculation in `EvalBasis` and `EvalGradientBasis`. If we ever found ourselves needing both info in the same routine, we can add a new function that returns both (i.e. `EvalBasisAndGradient`).
___
*[`multibody/fem/mpm-dev/BSpline.cc` line 51 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/7#-N2lmwET4RARSz8TNbvx:-N2lmwET4RARSz8TNbvy:bz20b6u) ([raw file](https://github.com/yiminlin-tri/drake/blob/f8cd27cbf0bf77600f149976e361a6b01102ad20/multibody/fem/mpm-dev/BSpline.cc#L51)):*
> ```cpp
>                              *(EvalGradient1DBasis(scale*(x(2)-position_(2))))
>                              *(Eval1DBasis(scale*(x(0)-position_(0))))
>                              *(Eval1DBasis(scale*(x(1)-position_(1)))));
> ```

This has been calculated 9 lines above. We can cache this.
___
*[`multibody/fem/mpm-dev/test/BSpline_test.cc` line 147 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/7#-N2lnk4L6xwjcsyxJSnj:-N2lnk4L6xwjcsyxJSnk:bod28ei) ([raw file](https://github.com/yiminlin-tri/drake/blob/f8cd27cbf0bf77600f149976e361a6b01102ad20/multibody/fem/mpm-dev/test/BSpline_test.cc#L147)):*
> ```cpp
>     // Iterate through all sampled points over [-1, 1]^3. Then all basis
>     // evaluated at sampled points shall be 1.0 by the partition of unity
>     // property of B-spline basis
> ```

nit, consider adding a comment here that we should expect the gradient to sum up to zero.

**Review by yiminlin-tri — COMMENTED** [review]
Fixed. Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/7#-:-N2m8roH-jULVemShdY9:b-d5q2i1)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/BSpline.cc` line 35 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/7#-N2ln-o-1DDBUpCDpu62:-N2m8q4F7Bc5NjXuFONt:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/f8cd27cbf0bf77600f149976e361a6b01102ad20/multibody/fem/mpm-dev/BSpline.cc#L35)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, there are some repeated calculation in `EvalBasis` and `EvalGradientBasis`. If we ever found ourselves needing both info in the same routine, we can add a new function that returns both (i.e. `EvalBasisAndGradient`).
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/BSpline.cc` line 51 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/7#-N2lmwET4RARSz8TNbvx:-N2m8oH8DNVxRGYw1OJt:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/f8cd27cbf0bf77600f149976e361a6b01102ad20/multibody/fem/mpm-dev/BSpline.cc#L51)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This has been calculated 9 lines above. We can cache this.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/BSpline_test.cc` line 147 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/7#-N2lnk4L6xwjcsyxJSnj:-N2lqFlU4UamgsVV0cVt:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/f8cd27cbf0bf77600f149976e361a6b01102ad20/multibody/fem/mpm-dev/test/BSpline_test.cc#L147)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, consider adding a comment here that we should expect the gradient to sum up to zero.
</blockquote></details>

Done

**Review by xuchen-han — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)

**Pull request merged**
