### PR TITLE
A Particles class to hold particles states

### PR DESCRIPTION
**Pull request by yiminlin-tri**
A simple particles class using structure of arrays design, with simple getters, setters.

---
This change is [Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/5)

### CODE REVIEW

**Review by xuchen-han — CHANGES_REQUESTED** [review]
:lgtm: with a concern about retrieving entire array of data vs retrieving data about a single particle. But we can always revisit this later.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/5#-:-N2SAYitCLSlHrdLB7Yg:b-1npq2f)* status: all files reviewed, 4 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/Particles.h` line 12 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/5#-N2S9GjO3M2GZiq_BZbK:-N2S9GjP6Qx-jEUBVfSz:b12zl9v) ([raw file](https://github.com/yiminlin-tri/drake/blob/a9734a413a271d2437bb2f8765f10b9a0daa1749/multibody/fem/mpm-dev/Particles.h#L12)):*
> ```objc
> 
> // A particles class holding vectors of particles' state
> class Particles {
> ```

I would have imagined that getting the entire array of quantities would be more useful than getting single entries.

e.g. `const std::vector<Vector3<double>>& get_positions() const;` instead of `const Vector3<double>& get_position() const;`

But we can move on with this and revisit this if needed.
___
*[`multibody/fem/mpm-dev/Particles.h` line 18 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/5#-N2S77X_5aU0i3vb8xS7:-N2S77X_5aU0i3vb8xS8:b-h8az7s) ([raw file](https://github.com/yiminlin-tri/drake/blob/a9734a413a271d2437bb2f8765f10b9a0daa1749/multibody/fem/mpm-dev/Particles.h#L18)):*
> ```objc
> 
>     int get_num_particles();
>     const Vector3<double>& get_position_at(int index) const;
> ```

nit, consider removing the `_at` postfix. 

e.g. get_position(int index).

The singular form and the return type indicates that this is a single particle's postion.
___
*[`multibody/fem/mpm-dev/Particles.h` line 21 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/5#-N2S6wvtBj06yhrB0wvt:-N2S6wvtBj06yhrB0wvu:b-9vrgyg) ([raw file](https://github.com/yiminlin-tri/drake/blob/a9734a413a271d2437bb2f8765f10b9a0daa1749/multibody/fem/mpm-dev/Particles.h#L21)):*
> ```objc
>     const Vector3<double>& get_velocity_at(int index) const;
>     const double& get_mass_at(int index) const;
>     const double& get_volume_at(int index) const;
> ```

We should be explicit that this is the reference configuration volume.
___
*[`multibody/fem/mpm-dev/Particles.h` line 23 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/5#-N2S7ZZmDLpY2qrQ1LlY:-N2S7ZZn9oKTl8XKwy2E:b-68gxhn) ([raw file](https://github.com/yiminlin-tri/drake/blob/a9734a413a271d2437bb2f8765f10b9a0daa1749/multibody/fem/mpm-dev/Particles.h#L23)):*
> ```objc
>     const double& get_volume_at(int index) const;
>     const Matrix3<double>& get_deformation_gradient_at(int index) const;
>     const Matrix3<double>& get_stress_at(int index) const;
> ```

We should be explicit about what stress this is? I suppose you meant Kirchhoff stress.
___
*[`multibody/fem/mpm-dev/Particles.h` line 33 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/5#-N2S7qcsBhDoBMTdK_ML:-N2S7qcsBhDoBMTdK_MM:b-6sdcea) ([raw file](https://github.com/yiminlin-tri/drake/blob/a9734a413a271d2437bb2f8765f10b9a0daa1749/multibody/fem/mpm-dev/Particles.h#L33)):*
> ```objc
>     void set_stress_at(int index, const Matrix3<double>& stress);
> 
>     void add_particle(const Vector3<double>& position,
> ```

BTW, this should be `AddParticle` because this could be expensive.
___
*[`multibody/fem/mpm-dev/Particles.cc` line 9 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/5#-N2S8sSN6uL6qs4U2Aa3:-N2S8sSN6uL6qs4U2Aa4:b-wwx078) ([raw file](https://github.com/yiminlin-tri/drake/blob/a9734a413a271d2437bb2f8765f10b9a0daa1749/multibody/fem/mpm-dev/Particles.cc#L9)):*
> ```cpp
> Particles::Particles(): num_particles_(0) {}
> 
> Particles::Particles(int num_particles) {
> ```

It's usually a better practice to invoke the constructors of the data members directly i.e.

```
Particles::Particles(int num_particles): num_particles_(num_particles), positions_(num_particles), velocities_(num_particles)... {}
```
___
*[`multibody/fem/mpm-dev/test/Particles_test.cc` line 15 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/5#-N2S8atr2_TVm3dKKewW:-N2S8atr2_TVm3dKKewX:b-vvrvxa) ([raw file](https://github.com/yiminlin-tri/drake/blob/a9734a413a271d2437bb2f8765f10b9a0daa1749/multibody/fem/mpm-dev/test/Particles_test.cc#L15)):*
> ```cpp
> constexpr double kEps = 4.0 * std::numeric_limits<double>::epsilon();
> 
> GTEST_TEST(ParticlesClassTest, RoundTrip) {
> ```

nit, the name "RoundTrip" is a bit confusing. I suppose this is from a copypaste.
___
*[`multibody/fem/mpm-dev/test/Particles_test.cc` line 104 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/5#-N2S8Qgj6DDuwF4Z5J05:-N2S8Qgk77pWS8WH8GJ_:b-oglpqg) ([raw file](https://github.com/yiminlin-tri/drake/blob/a9734a413a271d2437bb2f8765f10b9a0daa1749/multibody/fem/mpm-dev/test/Particles_test.cc#L104)):*
> ```cpp
>     EXPECT_EQ(particles.get_mass_at(2), mass1);
>     EXPECT_EQ(particles.get_volume_at(2), vol1);
>     EXPECT_TRUE(CompareMatrices(particles.get_deformation_gradient_at(2), dg1,
> ```

BTW, we usually use `F` to denote deformation gradient.

**Review by yiminlin-tri — COMMENTED** [review]
Sounds good. I will update if necessary when I make the PR on the transfer. Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/5#-:-N2SHbU690g2dUD3TJo9:bjlufbr)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/Particles.h` line 12 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/5#-N2S9GjO3M2GZiq_BZbK:-N2SHMwe4mIo4cwwnH1Z:btig14k) ([raw file](https://github.com/yiminlin-tri/drake/blob/a9734a413a271d2437bb2f8765f10b9a0daa1749/multibody/fem/mpm-dev/Particles.h#L12)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I would have imagined that getting the entire array of quantities would be more useful than getting single entries.

e.g. `const std::vector<Vector3<double>>& get_positions() const;` instead of `const Vector3<double>& get_position() const;`

But we can move on with this and revisit this if needed.
</blockquote></details>

Sounds good. I will mark as Done for now and revisit when necessary when I am implementing transfer. 
___
*[`multibody/fem/mpm-dev/Particles.h` line 18 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/5#-N2S77X_5aU0i3vb8xS7:-N2SDHQLDdHAZBcsiLku:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/a9734a413a271d2437bb2f8765f10b9a0daa1749/multibody/fem/mpm-dev/Particles.h#L18)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, consider removing the `_at` postfix. 

e.g. get_position(int index).

The singular form and the return type indicates that this is a single particle's postion.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/Particles.h` line 21 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/5#-N2S6wvtBj06yhrB0wvt:-N2SEVkE2fB8vKRpsO7f:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/a9734a413a271d2437bb2f8765f10b9a0daa1749/multibody/fem/mpm-dev/Particles.h#L21)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

We should be explicit that this is the reference configuration volume.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/Particles.h` line 23 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/5#-N2S7ZZmDLpY2qrQ1LlY:-N2SFx1W1zA6rOHvA2Cy:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/a9734a413a271d2437bb2f8765f10b9a0daa1749/multibody/fem/mpm-dev/Particles.h#L23)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

We should be explicit about what stress this is? I suppose you meant Kirchhoff stress.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/Particles.h` line 33 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/5#-N2S7qcsBhDoBMTdK_ML:-N2SGXC_4MsHmZsCBv2H:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/a9734a413a271d2437bb2f8765f10b9a0daa1749/multibody/fem/mpm-dev/Particles.h#L33)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, this should be `AddParticle` because this could be expensive.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/Particles.cc` line 9 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/5#-N2S8sSN6uL6qs4U2Aa3:-N2SHJbBEF5jSz6-2z4C:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/a9734a413a271d2437bb2f8765f10b9a0daa1749/multibody/fem/mpm-dev/Particles.cc#L9)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

It's usually a better practice to invoke the constructors of the data members directly i.e.

```
Particles::Particles(int num_particles): num_particles_(num_particles), positions_(num_particles), velocities_(num_particles)... {}
```
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/Particles_test.cc` line 15 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/5#-N2S8atr2_TVm3dKKewW:-N2SB_lR5xtv-zRYpQeD:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/a9734a413a271d2437bb2f8765f10b9a0daa1749/multibody/fem/mpm-dev/test/Particles_test.cc#L15)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, the name "RoundTrip" is a bit confusing. I suppose this is from a copypaste.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/Particles_test.cc` line 104 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/5#-N2S8Qgj6DDuwF4Z5J05:-N2SC_hiBBvmQKAQEOzi:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/a9734a413a271d2437bb2f8765f10b9a0daa1749/multibody/fem/mpm-dev/test/Particles_test.cc#L104)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, we usually use `F` to denote deformation gradient.
</blockquote></details>

Done

**Review by yiminlin-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/5#-:-N2SIHtq8InZ2YFRNhuW:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @xuchenhan-tri)

**Review by xuchen-han — APPROVED** [review]
two style nits. Feel free to merge after fixing.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/5#-:-N2SJ2WQ7lHOwqpXzDK8:b-e34f0i)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/Particles.h` line 33 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/5#-N2S7qcsBhDoBMTdK_ML:-N2SIfcZ1iR4QLJSxwvZ:b2tr9la) ([raw file](https://github.com/yiminlin-tri/drake/blob/a9734a413a271d2437bb2f8765f10b9a0daa1749/multibody/fem/mpm-dev/Particles.h#L33)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Done
</blockquote></details>

We don't usually use camelCase. addParticle->AddParticle.
___
*[`multibody/fem/mpm-dev/Particles.h` line 23 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/5#-N2SIseg2bpbMT9gZOkv:-N2SIseg2bpbMT9gZOkw:b-cr6koa) ([raw file](https://github.com/yiminlin-tri/drake/blob/15574b0517131f582b064f3ee66f15caa5e58c8c/multibody/fem/mpm-dev/Particles.h#L23)):*
> ```objc
>     const double& get_reference_volume(int index) const;
>     const Matrix3<double>& get_deformation_gradient(int index) const;
>     const Matrix3<double>& get_Kirchhoff_stress(int index) const;
> ```

no caps in snake_case.

Kirchhoff->kirchhoff.

**Review by xuchen-han — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)

**Review by yiminlin-tri — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/5#-:-N2SKsQy4IWvO-fp5_-u:b-ucfknh)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/Particles.h` line 33 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/5#-N2S7qcsBhDoBMTdK_ML:-N2SKqZd1xOLszucjXqy:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/a9734a413a271d2437bb2f8765f10b9a0daa1749/multibody/fem/mpm-dev/Particles.h#L33)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

We don't usually use camelCase. addParticle->AddParticle.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/Particles.h` line 23 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/5#-N2SIseg2bpbMT9gZOkv:-N2SK8YF8cQp5hlUiGWA:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/15574b0517131f582b064f3ee66f15caa5e58c8c/multibody/fem/mpm-dev/Particles.h#L23)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

no caps in snake_case.

Kirchhoff->kirchhoff.
</blockquote></details>

Done

**Review by yiminlin-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)

**Pull request merged**
