### PR TITLE
MPM transfer - grid to particles

### PR DESCRIPTION
**Pull request by yiminlin-tri**
This change is [Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/12)

### CODE REVIEW

**Review by yiminlin-tri — COMMENTED** [review]
@xuchenhan-tri Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/12#-:-N3Rk0qj2F5a7vfCPqBU:b7am51h)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 703 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/12#-N3Rk8Ov3pt81w4jU-rA:-N3Rk8Ov3pt81w4jU-rB:b-ctgqwy) ([raw file](https://github.com/yiminlin-tri/drake/blob/3c54ac81639f8b9e1d835259c24bb5747b5fad1b/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L703)):*
> ```cpp
>     }
> 
>     void checkG2PMassVelocity1() {
> ```

Not so obvious to find a good test case for deformation gradient.

**Review by yiminlin-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/12)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 703 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/12#-N3Rk8Ov3pt81w4jU-rA:-N3Rl-nK7JEIKRNN3Bn4:b-6hq39z) ([raw file](https://github.com/yiminlin-tri/drake/blob/3c54ac81639f8b9e1d835259c24bb5747b5fad1b/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L703)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Not so obvious to find a good test case for deformation gradient.
</blockquote></details>

I will hardcode one test case for now, and I will update soon.

**Review by xuchen-han — CHANGES_REQUESTED** [review]
I reviewed the implementation. Looks good!

FYI, we will need the grid node positions and the particle positions in G2P when we do APIC, so we may need to modify the function signature little bit then.

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/12#-:-N3Roj485gHzWvVZR2d0:b-u5kn2i)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 85 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/12#-N3Ro2uj7Tr2JI7Ryix6:-N3Ro2uk0aEFT86cpnL8:b-paewa3) ([raw file](https://github.com/yiminlin-tri/drake/blob/3c54ac81639f8b9e1d835259c24bb5747b5fad1b/multibody/fem/mpm-dev/MPMTransfer.cc#L85)):*
> ```cpp
>         for (int p = p_start; p < p_end; ++p) {
>             UpdateParticleStates(batch_velocities, dt, p,
>                                  &vp_new, &F_scale, particles);
> ```

Do we need to write to `F_scale` and `vp_new` here?
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 261 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/12#-N3RmoSj7nHA6AcGSwJr:-N3RmoSj7nHA6AcGSwJs:b7yuh02) ([raw file](https://github.com/yiminlin-tri/drake/blob/3c54ac81639f8b9e1d835259c24bb5747b5fad1b/multibody/fem/mpm-dev/MPMTransfer.cc#L261)):*
> ```cpp
>                                        double dt, int p,
>                                        EigenPtr<Vector3<double>> vp_new,
>                                        EigenPtr<Matrix3<double>> F_scale,
> ```

Can we call this something like "grad_vp_new" to be more expressive?

**Review by yiminlin-tri — COMMENTED** [review]
Sure, sounds good. I will modify when I am working on APIC.

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/12#-:-N3RqQ5H59N60KQ_8vly:b-da31ai)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 85 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/12#-N3Ro2uj7Tr2JI7Ryix6:-N3RpicEBK1iQ-ZqYhOy:b-p4gxyt) ([raw file](https://github.com/yiminlin-tri/drake/blob/3c54ac81639f8b9e1d835259c24bb5747b5fad1b/multibody/fem/mpm-dev/MPMTransfer.cc#L85)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Do we need to write to `F_scale` and `vp_new` here?
</blockquote></details>

I am not so sure about this. I think it depends on the price of stack allocation. I can also make a local F_scale and vp_new everytime I call UpdateParticleStates. Is there a smarter way to do it without allocation?
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 261 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/12#-N3RmoSj7nHA6AcGSwJr:-N3RqBej7grvnPzUMczX:b-ik4oq7) ([raw file](https://github.com/yiminlin-tri/drake/blob/3c54ac81639f8b9e1d835259c24bb5747b5fad1b/multibody/fem/mpm-dev/MPMTransfer.cc#L261)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Can we call this something like "grad_vp_new" to be more expressive?
</blockquote></details>

Sure - but this variable is the particle velocity right? So the grad stands for?

**Review by xuchen-han — CHANGES_REQUESTED** [review]
:lgtm: with a few comments, PTAL.

BTW, make sure to choose "squash and merge" when merging and clean up the commit messages.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/12#-:-N3V83-z7vCtR188XZjd:b-lacaiv)* status: all files reviewed (commit messages unreviewed), 8 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 85 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/12#-N3Ro2uj7Tr2JI7Ryix6:-N3V2KXZCeCoLtk4ue9x:b-qbrtd) ([raw file](https://github.com/yiminlin-tri/drake/blob/3c54ac81639f8b9e1d835259c24bb5747b5fad1b/multibody/fem/mpm-dev/MPMTransfer.cc#L85)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

I am not so sure about this. I think it depends on the price of stack allocation. I can also make a local F_scale and vp_new everytime I call UpdateParticleStates. Is there a smarter way to do it without allocation?
</blockquote></details>

I don't think the stack allocation will be a significant cost here. All it does is just moving the stack pointer around.
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 261 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/12#-N3RmoSj7nHA6AcGSwJr:-N3V1hiD5-Pj48_1tkof:bbudpgj) ([raw file](https://github.com/yiminlin-tri/drake/blob/3c54ac81639f8b9e1d835259c24bb5747b5fad1b/multibody/fem/mpm-dev/MPMTransfer.cc#L261)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Sure - but this variable is the particle velocity right? So the grad stands for?
</blockquote></details>

No I meant the `F_scale` argument. It's the velocity gradient evaluated at the particle's position, and thus the name `grad`.
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 81 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/12#-N3V4XdS8vES4EoScFwl:-N3V4XdT0RM6hF6d1u-q:b1ucyrm) ([raw file](https://github.com/yiminlin-tri/drake/blob/9c27a20cfc756c99ea4684476bfb221391c04423/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L81)):*
> ```cpp
>                                     std::numeric_limits<double>::epsilon()));
> 
>         // Check particles in the correct ordering after sorting
> ```

nit stale comment.
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 703 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/12#-N3V6Hy61K12f2GM5ak7:-N3V6Hy61K12f2GM5ak8:b-wd6e3s) ([raw file](https://github.com/yiminlin-tri/drake/blob/9c27a20cfc756c99ea4684476bfb221391c04423/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L703)):*
> ```cpp
>     }
> 
>     void checkG2PForce() {
> ```

This test seems to be testing that the deformation gradient of a particle is unchanged in the transfer if the grid velocity field is constant and doesn't have anything to do with force? Consider documenting it as is and/or coming up with a better name.
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 757 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/12#-N3V4zKu94aB9hp3QKNZ:-N3V4zKu94aB9hp3QKN_:b83d6i8) ([raw file](https://github.com/yiminlin-tri/drake/blob/9c27a20cfc756c99ea4684476bfb221391c04423/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L757)):*
> ```cpp
>         // Since the velocity field is constant, the deformation gradient
>         // doesn't change with respect to time
>         EXPECT_TRUE(CompareMatrices(tau_p, particles_->get_kirchhoff_stress(0),
> ```

Should we test the deformation gradient instead of the stress here?
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 766 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/12#-N3V5HrFDQYMFWnFTN07:-N3V5HrFDQYMFWnFTN08:bholy3) ([raw file](https://github.com/yiminlin-tri/drake/blob/9c27a20cfc756c99ea4684476bfb221391c04423/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L766)):*
> ```cpp
>         double sum_mass_particle, sum_mass_grid;
>         Vector3<double> sum_momentum_particle, sum_momentum_grid;
>         double dt = 0.0;
> ```

Not sure how I feel about dt = 0 here. There probably should be a DRAKE_DEMAND/DRAKE_ASSERT inside G2P that verifies dt > 0.
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 808 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/12#-N3V64Wl9CxVA5ypKDv5:-N3V64Wl9CxVA5ypKDv6:bupsa83) ([raw file](https://github.com/yiminlin-tri/drake/blob/9c27a20cfc756c99ea4684476bfb221391c04423/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L808)):*
> ```cpp
>     }
> 
>     void checkG2PMassVelocity2() {
> ```

nit I'm struggling to see the difference between this test and the one above. Could you explain?

As this test file grows, it becomes harder to keep track of all the tests and see which functionalities/invariants are tested. I'd recommend follow up with PR to clean up -- come up with more descriptive names (e.g. TestFoo1, TestFoo2, etc don't immediately communicate how they are different and why they both should exist) and documenting clearly what each test case is testing.

Also, it would help with readability if we could distill a few testing routines instead of copying them over and again. For example, we could have a helper function like `void GetTotalParticleMassAndMomentum(const Particles&, double* mass_p, double* momentum_p)`

**Review by yiminlin-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/12)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 85 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/12#-N3Ro2uj7Tr2JI7Ryix6:-N3VBUlI1ZsWt2R3dCqk:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/3c54ac81639f8b9e1d835259c24bb5747b5fad1b/multibody/fem/mpm-dev/MPMTransfer.cc#L85)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I don't think the stack allocation will be a significant cost here. All it does is just moving the stack pointer around.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 261 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/12#-N3RmoSj7nHA6AcGSwJr:-N3VBoFF7FX5NG0fm7dS:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/3c54ac81639f8b9e1d835259c24bb5747b5fad1b/multibody/fem/mpm-dev/MPMTransfer.cc#L261)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

No I meant the `F_scale` argument. It's the velocity gradient evaluated at the particle's position, and thus the name `grad`.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 81 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/12#-N3V4XdS8vES4EoScFwl:-N3VCHgBEGHMQKQU39-F:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/9c27a20cfc756c99ea4684476bfb221391c04423/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L81)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit stale comment.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 703 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/12#-N3V6Hy61K12f2GM5ak7:-N3VDXm74vwEFqSEvwod:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/9c27a20cfc756c99ea4684476bfb221391c04423/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L703)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This test seems to be testing that the deformation gradient of a particle is unchanged in the transfer if the grid velocity field is constant and doesn't have anything to do with force? Consider documenting it as is and/or coming up with a better name.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 757 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/12#-N3V4zKu94aB9hp3QKNZ:-N3VEZIC6pVHmdvHEMrJ:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/9c27a20cfc756c99ea4684476bfb221391c04423/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L757)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Should we test the deformation gradient instead of the stress here?
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 766 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/12#-N3V5HrFDQYMFWnFTN07:-N3VCa2G5Vt9NTHqABUI:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/9c27a20cfc756c99ea4684476bfb221391c04423/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L766)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Not sure how I feel about dt = 0 here. There probably should be a DRAKE_DEMAND/DRAKE_ASSERT inside G2P that verifies dt > 0.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 808 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/12#-N3V64Wl9CxVA5ypKDv5:-N3VEn5I5zw9Ci-hgyDJ:bc69ha4) ([raw file](https://github.com/yiminlin-tri/drake/blob/9c27a20cfc756c99ea4684476bfb221391c04423/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L808)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit I'm struggling to see the difference between this test and the one above. Could you explain?

As this test file grows, it becomes harder to keep track of all the tests and see which functionalities/invariants are tested. I'd recommend follow up with PR to clean up -- come up with more descriptive names (e.g. TestFoo1, TestFoo2, etc don't immediately communicate how they are different and why they both should exist) and documenting clearly what each test case is testing.

Also, it would help with readability if we could distill a few testing routines instead of copying them over and again. For example, we could have a helper function like `void GetTotalParticleMassAndMomentum(const Particles&, double* mass_p, double* momentum_p)`
</blockquote></details>

So one test called checkP2GMassVelocity1() and one called checkP2GMassVelocity2()... The particles in both cases are different. I totally agree, the tests are very disorganized, I will clean up the tests in a future PR. Thanks!

**Review by yiminlin-tri — COMMENTED** [review]
Gotcha, thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/12#-:-N3VHPew0TgDHZG--rxz:by5s5kf)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @xuchenhan-tri)

**Review by yiminlin-tri — COMMENTED** [review]
+@xuchenhan-tri

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/12#-:-N3VHuCu6ipelBg-cnly:bputuby)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @xuchenhan-tri)

**Review by xuchen-han — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/12)* status: all files reviewed, 2 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 808 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/12#-N3V64Wl9CxVA5ypKDv5:-N3VRnjD4Nmhb738tf-j:b-wmvcv0) ([raw file](https://github.com/yiminlin-tri/drake/blob/9c27a20cfc756c99ea4684476bfb221391c04423/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L808)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

So one test called checkP2GMassVelocity1() and one called checkP2GMassVelocity2()... The particles in both cases are different. I totally agree, the tests are very disorganized, I will clean up the tests in a future PR. Thanks! 
</blockquote></details>

Ah I see. I think there's some refactoring that we can do to cut down the repetition.

**Review by xuchen-han — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/12)* status: all files reviewed, 2 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 703 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/12#-N3Rk8Ov3pt81w4jU-rA:-N3VSF__2hag5BvrW0-5:b5rph7q) ([raw file](https://github.com/yiminlin-tri/drake/blob/3c54ac81639f8b9e1d835259c24bb5747b5fad1b/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L703)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

I will hardcode one test case for now, and I will update soon.
</blockquote></details>

BTW This comment is blocking.

**Review by yiminlin-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/12)* status: all files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 808 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/12#-N3V64Wl9CxVA5ypKDv5:-N3VT-jvApj3-yUCZoPV:b-cstnkg) ([raw file](https://github.com/yiminlin-tri/drake/blob/9c27a20cfc756c99ea4684476bfb221391c04423/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L808)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Ah I see. I think there's some refactoring that we can do to cut down the repetition.
</blockquote></details>

I agree

**Review by yiminlin-tri — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/12)* status: all files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)

**Pull request merged**
