### PR TITLE
ExternalForce class: add external forces to grid points

### PR DESCRIPTION
**Pull request by yiminlin-tri**
This change is [Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/15)

### CODE REVIEW

**Review by yiminlin-tri — COMMENTED** [review]
+@xuchenhan-tri Only added gravitational force since it seems like the only necessary external force we need. Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/15#-:-N4--ge7AodDSN8SGZOp:bwkb287)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @xuchenhan-tri)

**Review by xuchen-han — CHANGES_REQUESTED** [review]
:lgtm: with two thoughts.
1. Consider calling the class GravitationalForce or similar if we really only have gravity as the only external force in the foreseeable future.
2. Make the gravity vector configurable. So we can easily change it if need, e.g to zero or to a different direction (which sometimes serves as a good testing strategy).

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/15#-:-N4-7k682BCjM9gzv2mv:b3ko246)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)

**Review by yiminlin-tri — COMMENTED** [review]
+@xuchenhan-tri Fixed, thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/15#-:-N4-Fk7S6ytmY3QqbYW2:b7jd5c2)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @xuchenhan-tri)

**Review by xuchen-han — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/GravitationalForce.cc` line 11 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/15#-N4-FvzbDQ7-QvVpfaJh:-N4-FvzbDQ7-QvVpfaJi:bootmww) ([raw file](https://github.com/yiminlin-tri/drake/blob/4b8178beb01d1b2b1b98dc29c8db70fa84c922d3/multibody/fem/mpm-dev/GravitationalForce.cc#L11)):*
> ```cpp
> 
> GravitationalForce::GravitationalForce(Vector3<double> g):
>                                 gravitational_acceleration_(std::move(g)) {}
> ```

FYI, unlike moving something like `std::vector`, there isn't much saving on moving a fixed size vector. It's most likely allocated on the stack anyway, i.e. The move constructor should be identical to the copy constructor.

**Review by yiminlin-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)

**Pull request merged**
