### PR TITLE
MPM transfer - Preallocate bases evaluations and gradient evals

### PR DESCRIPTION
**Pull request by yiminlin-tri**
This change is [Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/10)

### CODE REVIEW

**Review by yiminlin-tri — COMMENTED** [review]
@xuchenhan-tri Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/10#-:-N30Kqi9BKcXaBmWvMkV:b7am51h)* status: 0 of 6 files reviewed, 1 unresolved discussion

___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 73 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/10#-N30KY2bEkGDN-U4ca5h:-N30KY2bEkGDN-U4ca5i:b-b4lvvn) ([raw file](https://github.com/yiminlin-tri/drake/blob/55652bd9a14be0fd8876f0ffb105166f54c1d443/multibody/fem/mpm-dev/MPMTransfer.cc#L73)):*
> ```cpp
>     }
>     }
> ```

The ordering of the loop is kind of subtle. I loop through batches -> basis -> particles to avoid calculating idx_local too much. But looping through batches -> particles -> basis seems more natural. What do you think?

**Review by xuchen-han — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/10)* status: all files reviewed, 6 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 23 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/10#-N30ZXipBBUO4ueIaECi:-N30ZXipBBUO4ueIaECj:b-eoaf4l) ([raw file](https://github.com/yiminlin-tri/drake/blob/55652bd9a14be0fd8876f0ffb105166f54c1d443/multibody/fem/mpm-dev/MPMTransfer.h#L23)):*
> ```objc
>     MPMTransfer() {}
> 
>     void SetUpTransfer(const Grid& grid, Particles* particles);
> ```

Need to document what is does and how it should be used (e.g. one must invoke this before doing transfers, otherwise the results would be incorrect) etc.
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 73 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/10#-N30KY2bEkGDN-U4ca5h:-N30XdgJBJkbEy0hJQEq:be3kx7h) ([raw file](https://github.com/yiminlin-tri/drake/blob/55652bd9a14be0fd8876f0ffb105166f54c1d443/multibody/fem/mpm-dev/MPMTransfer.cc#L73)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

The ordering of the loop is kind of subtle. I loop through batches -> basis -> particles to avoid calculating idx_local too much. But looping through batches -> particles -> basis seems more natural. What do you think?
</blockquote></details>

I think either is fine, but it'd would be nice to see the responsibility spread out a little bit more instead of trying to do everything in this function here.

e.g.

```
for (const auto& [flat_index, 3d_index] : grid.GetIndexes()) {
    p_end = p_start + batch_sizes_[flat_index];
    for (int p = p_start; p < p_end; ++p) {
        const Vector3<double>& xp = particles.get_positions(p);
        EvalBasisOnBatch(xp, grid, 3d_index, &bases);
    }
}
```
 would arguably make the code more readable and easier to reason about. Optional.
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 86 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/10#-N30WguG1rOCHs7QJl26:-N30WguH1OAao7qI9NfX:b-rmsqr8) ([raw file](https://github.com/yiminlin-tri/drake/blob/55652bd9a14be0fd8876f0ffb105166f54c1d443/multibody/fem/mpm-dev/MPMTransfer.cc#L86)):*
> ```cpp
>         for (int j = bj - 1; j <= bj + 1; ++j) {
>         for (int i = bi - 1; i <= bi + 1; ++i) {
>         if (grid.in_index_range(i, j, k)) {
> ```

If this predicate fails, it means that the simulation is in trouble (particles are going out of bound). We should throw an error message.
___
*[`multibody/fem/mpm-dev/test/Grid_test.cc` line 99 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/10#-N30_-dT9Mvfd9H3gyDj:-N30_-dT9Mvfd9H3gyDk:b40ybc5) ([raw file](https://github.com/yiminlin-tri/drake/blob/55652bd9a14be0fd8876f0ffb105166f54c1d443/multibody/fem/mpm-dev/test/Grid_test.cc#L99)):*
> ```cpp
> }
> 
> GTEST_TEST(GridClassTest, TestIndexUtil) {
> ```

nit The test name should be "Expand1DIndex` to make it clear which function is being tested.
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 262 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/10#-N30_mA6BfCAJdE2sMq9:-N30_mA6BfCAJdE2sMqA:b-hx3fe6) ([raw file](https://github.com/yiminlin-tri/drake/blob/55652bd9a14be0fd8876f0ffb105166f54c1d443/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L262)):*
> ```cpp
>         // Set particles' positions to be on grid points
>         pc = 0;
>         for (int k = bottom_corner(2); k < bottom_corner(2)+num_gridpt_1D(2);
> ```

If the particles are set up this way, does it actually require any sorting? If not, perhaps best to set up a more general case.
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 282 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/10#-N30aFkC5Zu8NGEC1Z1C:-N30aFkC5Zu8NGEC1Z1D:bc1sqjm) ([raw file](https://github.com/yiminlin-tri/drake/blob/55652bd9a14be0fd8876f0ffb105166f54c1d443/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L282)):*
> ```cpp
>         // 0, by the partition of unity property.
>         for (int p = 0; p < num_particles; ++p) {
>             EXPECT_EQ(mpm_transfer.bases_val_particles_[p][13], 0.75*0.75*0.75);
> ```

nit, it's odd to see particle index being used where batch indexes are needed. Usually these type of implicit conversions are error-prone, and it's better to explicitly write down `int batch_index = p` and comment on why that should the case.

**Review by yiminlin-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/10)* status: all files reviewed, 4 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 23 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/10#-N30ZXipBBUO4ueIaECi:-N30cROgAtFCbQigLBhh:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/55652bd9a14be0fd8876f0ffb105166f54c1d443/multibody/fem/mpm-dev/MPMTransfer.h#L23)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Need to document what is does and how it should be used (e.g. one must invoke this before doing transfers, otherwise the results would be incorrect) etc.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 73 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/10#-N30KY2bEkGDN-U4ca5h:-N31APgV87L22c7wuIrw:b-wq9wp0) ([raw file](https://github.com/yiminlin-tri/drake/blob/55652bd9a14be0fd8876f0ffb105166f54c1d443/multibody/fem/mpm-dev/MPMTransfer.cc#L73)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I think either is fine, but it'd would be nice to see the responsibility spread out a little bit more instead of trying to do everything in this function here.

e.g.

```
for (const auto& [flat_index, 3d_index] : grid.GetIndexes()) {
    p_end = p_start + batch_sizes_[flat_index];
    for (int p = p_start; p < p_end; ++p) {
        const Vector3<double>& xp = particles.get_positions(p);
        EvalBasisOnBatch(xp, grid, 3d_index, &bases);
    }
}
```
 would arguably make the code more readable and easier to reason about. Optional.
</blockquote></details>

Done with thanks - The code looks a lot readable!
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 86 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/10#-N30WguG1rOCHs7QJl26:-N30cvhq5-IdAsaq1bby:b-t1u9cf) ([raw file](https://github.com/yiminlin-tri/drake/blob/55652bd9a14be0fd8876f0ffb105166f54c1d443/multibody/fem/mpm-dev/MPMTransfer.cc#L86)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

If this predicate fails, it means that the simulation is in trouble (particles are going out of bound). We should throw an error message.
</blockquote></details>

I think this predicate determines whether a basis is out of bound. for looping (i, j, k) is looping through the batches, so in_index_range(i, j, k) determining whether a batch is in the index range. Batches have one-to-one correspondence to the basis, so we are equivalently checking whether a basis is out of bound. If the basis is out of bound, we skip evaluating this basis on the particles in the batch. What do you think? 
___
*[`multibody/fem/mpm-dev/test/Grid_test.cc` line 99 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/10#-N30_-dT9Mvfd9H3gyDj:-N30dRY311dnckuc2bUy:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/55652bd9a14be0fd8876f0ffb105166f54c1d443/multibody/fem/mpm-dev/test/Grid_test.cc#L99)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit The test name should be "Expand1DIndex` to make it clear which function is being tested.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 262 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/10#-N30_mA6BfCAJdE2sMq9:-N30dTlI8pSMNcrTNDpi:b-5xcgiy) ([raw file](https://github.com/yiminlin-tri/drake/blob/55652bd9a14be0fd8876f0ffb105166f54c1d443/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L262)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

If the particles are set up this way, does it actually require any sorting? If not, perhaps best to set up a more general case.
</blockquote></details>

Not really. I update the case. Thanks!
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 282 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/10#-N30aFkC5Zu8NGEC1Z1C:-N31B6y31KqxqLh4wWPy:b-yj0l0y) ([raw file](https://github.com/yiminlin-tri/drake/blob/55652bd9a14be0fd8876f0ffb105166f54c1d443/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L282)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, it's odd to see particle index being used where batch indexes are needed. Usually these type of implicit conversions are error-prone, and it's better to explicitly write down `int batch_index = p` and comment on why that should the case.
</blockquote></details>

Can you elaborate a little bit? bases_val_particles_ is an array of length (# of particles), so we should use particle index in this case?

**Review by xuchen-han — CHANGES_REQUESTED** [review]
I have two lingering questions. PTAL.

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/10#-:-N31IP0n2-ODbSl1xSWI:b2px0mp)* status: all files reviewed, 2 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/Grid.h` line 75 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/10#-N31GzhYBQJe0oWrqJf4:-N31GzhYBQJe0oWrqJf5:b749d3l) ([raw file](https://github.com/yiminlin-tri/drake/blob/b5a628bc1d51efb5ec827c1ed63046eb375f2051/multibody/fem/mpm-dev/Grid.h#L75)):*
> ```objc
>     // Get the vector of 1D and 3D indices of grid points, ordered
>     // lexiographically
>     std::vector<std::pair<int, Vector3<int>>> GetIndices() const;
> ```

Could we precompute this and return a const reference instead?
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 86 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/10#-N30WguG1rOCHs7QJl26:-N31Hnlp0JwY9nPRANaW:b-uh8lsx) ([raw file](https://github.com/yiminlin-tri/drake/blob/55652bd9a14be0fd8876f0ffb105166f54c1d443/multibody/fem/mpm-dev/MPMTransfer.cc#L86)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

I think this predicate determines whether a basis is out of bound. for looping (i, j, k) is looping through the batches, so in_index_range(i, j, k) determining whether a batch is in the index range. Batches have one-to-one correspondence to the basis, so we are equivalently checking whether a basis is out of bound. If the basis is out of bound, we skip evaluating this basis on the particles in the batch. What do you think? 
</blockquote></details>

I think if this predicate fails, then it means a particle is trying to transfer data to a nonexistent grid node. Do you agree? If that's the case, we should abort the simulation right away.
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 282 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/10#-N30aFkC5Zu8NGEC1Z1C:-N31Gj2WAi5l6jbAgnEx:bcwjhrk) ([raw file](https://github.com/yiminlin-tri/drake/blob/55652bd9a14be0fd8876f0ffb105166f54c1d443/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L282)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Can you elaborate a little bit? bases_val_particles_ is an array of length (# of particles), so we should use particle index in this case?
</blockquote></details>

I was mistaken! Retracted.

**Review by yiminlin-tri — COMMENTED** [review]
Replied - thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/10#-:-N31PhSe5unl0OekG9FO:b-xcxeg7)* status: all files reviewed, 2 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/Grid.h` line 75 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/10#-N31GzhYBQJe0oWrqJf4:-N31L8A_69GHBBn2oRKV:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/b5a628bc1d51efb5ec827c1ed63046eb375f2051/multibody/fem/mpm-dev/Grid.h#L75)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Could we precompute this and return a const reference instead?
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 86 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/10#-N30WguG1rOCHs7QJl26:-N31M8Q3DxYlknBJjFOV:bj3gkqw) ([raw file](https://github.com/yiminlin-tri/drake/blob/55652bd9a14be0fd8876f0ffb105166f54c1d443/multibody/fem/mpm-dev/MPMTransfer.cc#L86)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I think if this predicate fails, then it means a particle is trying to transfer data to a nonexistent grid node. Do you agree? If that's the case, we should abort the simulation right away.
</blockquote></details>

Yes, I agree. But I am still don't understand whether we should abort the simulation. 
So let's say if (grid.in_index_range(i, j, k)) == true, then the grid node is a valid node in the domain, we do the operation. 
If (grid.in_index_range(i, j, k)) == false, in the code, I just didn't do anything, so I didn't transfer any information to the nonexistent grid point. 
x - o - o
x - o - o
x - x - x
As an example, imagine we have 4 grid points o in 2D. A single particle is located at the lower left gridpoint. x denotes the invalid grid points (not in the Grid) 
Then, for example, we are doing P2G. The for (i, j, k) loop loop through these **9** grid points, although they are not all valid. Then the particle should transfer the info to all four grid points o in the domain by the predicate if (grid.in_index_range(i, j, k)) == true. Then if (grid.in_index_range(i, j, k)) == false, or on the x, we don't do anything. This predicate is used as a way to check whether a grid point is o or x. What's your though on this? Thanks!  
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 282 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/10#-N30aFkC5Zu8NGEC1Z1C:-N31LFct7T3uI-RO85GE:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/55652bd9a14be0fd8876f0ffb105166f54c1d443/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L282)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I was mistaken! Retracted.
</blockquote></details>

Done

**Review by yiminlin-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/10)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 86 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/10#-N30WguG1rOCHs7QJl26:-N31Q4-w9S7GXpvIkEyr:bcj1jvo) ([raw file](https://github.com/yiminlin-tri/drake/blob/55652bd9a14be0fd8876f0ffb105166f54c1d443/multibody/fem/mpm-dev/MPMTransfer.cc#L86)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Yes, I agree. But I am still don't understand whether we should abort the simulation. 
So let's say if (grid.in_index_range(i, j, k)) == true, then the grid node is a valid node in the domain, we do the operation. 
If (grid.in_index_range(i, j, k)) == false, in the code, I just didn't do anything, so I didn't transfer any information to the nonexistent grid point. 
x - o - o
x - o - o
x - x - x
As an example, imagine we have 4 grid points o in 2D. A single particle is located at the lower left gridpoint. x denotes the invalid grid points (not in the Grid) 
Then, for example, we are doing P2G. The for (i, j, k) loop loop through these **9** grid points, although they are not all valid. Then the particle should transfer the info to all four grid points o in the domain by the predicate if (grid.in_index_range(i, j, k)) == true. Then if (grid.in_index_range(i, j, k)) == false, or on the x, we don't do anything. This predicate is used as a way to check whether a grid point is o or x. What's your though on this? Thanks!  

</blockquote></details>

x - o - o
x - m - o
x - x - x

m is the particle location

**Review by xuchen-han — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/10)* status: all files reviewed, 2 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/Grid.cc` line 109 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/10#-N31SEQa-IDEwwoPrKig:-N31SEQa-IDEwwoPrKih:b-8m60qr) ([raw file](https://github.com/yiminlin-tri/drake/blob/1315a9e856b9256c4905284e8ab3bab4d5ce5376/multibody/fem/mpm-dev/Grid.cc#L109)):*
> ```cpp
> }
> 
> const std::vector<std::pair<int, Vector3<int>>>& Grid::GetIndices() const {
> ```

minor: this should be get_indices() instead (getter).
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 86 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/10#-N30WguG1rOCHs7QJl26:-N31RgzL1zrOM6tyk2G2:b-jb4vcg) ([raw file](https://github.com/yiminlin-tri/drake/blob/55652bd9a14be0fd8876f0ffb105166f54c1d443/multibody/fem/mpm-dev/MPMTransfer.cc#L86)):*
We are losing information when a particle tries to transfer to a nonexistant grid node.

For example, we we do P2G followed up G2P, we'd expect the momentum to be conserved (if there's no boundary condition). In this setup,
> x - o - o
x - m - o
x - x - x

that won't be true.

**Review by yiminlin-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/10)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/Grid.cc` line 109 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/10#-N31SEQa-IDEwwoPrKig:-N31TksN2sMQ9m0rzGdD:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/1315a9e856b9256c4905284e8ab3bab4d5ce5376/multibody/fem/mpm-dev/Grid.cc#L109)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

minor: this should be get_indices() instead (getter).
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 86 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/10#-N30WguG1rOCHs7QJl26:-N31Yx3XCbS7EL6DCqmQ:bqapa2i) ([raw file](https://github.com/yiminlin-tri/drake/blob/55652bd9a14be0fd8876f0ffb105166f54c1d443/multibody/fem/mpm-dev/MPMTransfer.cc#L86)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

We are losing information when a particle tries to transfer to a nonexistant grid node.

For example, we we do P2G followed up G2P, we'd expect the momentum to be conserved (if there's no boundary condition). In this setup,
> x - o - o
x - m - o
x - x - x

that won't be true.
</blockquote></details>

I put the discussion here again for reference. For example, on this grid:
o - o - o - o - o
o - o - o - o - o
o - o - o - o - o
o - o - o - o - o
o - o - o - o - o
The particles can be only in the inner 3x3 grid. And in the example in the comment,
o - o
o - o
it is not a valid domain at all, since any particle in the grid will lose information during the transfer. (Quadratic BSpline is not a nodal basis, so information are lost when the support of the basis is not included in the actual grid)

**Review by xuchen-han — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)

**Pull request merged**
