### PR TITLE
Add Poisson disk sampling

### PR DESCRIPTION
**Pull request by yiminlin-tri**
This change is [Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/17)

### CODE REVIEW

**Review by yiminlin-tri — COMMENTED** [review]
+@xuchenhan-tri Poisson disk sampling with support to Vector3

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/17#-:-N44YR-_CUXw3C8YZe1-:boq1kmv)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @xuchenhan-tri)

**Review by xuchen-han — CHANGES_REQUESTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/17#-:-N44ctemCNrxyC4CFHcj:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/poisson_disk_sampling.h` line 562 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/17#-N44clf57qYAWGhaUP7C:-N44clf57qYAWGhaUP7D:b-kjw411) ([raw file](https://github.com/yiminlin-tri/drake/blob/a8a87d4220586652211eb9b5437eb86e98ac871d/multibody/fem/mpm-dev/poisson_disk_sampling.h#L562)):*
> ```objc
> };
> 
> // Specialization of vector traits for Vector3
> ```

Optional
```
// Specialization of vector traits for Vector3
template <>
struct VecTraits<drake::Vector3<double>> {
  using ValueType = typename drake::Vector3<double>::Scalar;
  static constexpr auto kSize = 3;

  static ValueType Get(const drake::Vector3<double>& vec,
                       const std::size_t i)  {
    return vec(i);
  }

  static void Set(drake::Vector3<double>* vec,
                  const std::size_t i, const ValueType val) {
    (*vec)(i) = val;
  }
};
```

**Review by yiminlin-tri — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/17#-:-N44e0GD9kwedXBFotOU:bg7igkv)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @xuchenhan-tri)

**Review by xuchen-han — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/17)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)

**Review by xuchen-han — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/17)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)

**Pull request merged**
