### PR TITLE
[mpm-dev] Initial spatial velocity

### PR DESCRIPTION
**Pull request by yiminlin-tri**
This change is [Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/22)

### CODE REVIEW

**Review by yiminlin-tri — COMMENTED** [review]
+@xuchenhan-tri Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/22#-:-N5kUdzYEGFFolVNFtZ0:b6w1hxi)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @xuchenhan-tri)

**Review by xuchen-han — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/22)* status: all files reviewed, 2 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/MPMDriver.h` line 37 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/22#-N5kcOsMERclbswicHNa:-N5kcOsMERclbswicHNb:b40hx0o) ([raw file](https://github.com/yiminlin-tri/drake/blob/bc6078dd80f9ef989266022bd20714b06adf677c/multibody/fem/mpm-dev/MPMDriver.h#L37)):*
> ```objc
>         // has uniform density and velocity.
>         double density;
>         multibody::SpatialVelocity<double> initial_velocity;
> ```

nit, worth pointing out that this is is `V_WB`, the object B's spatial velocity measured and expressed in world frame.
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 80 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/22#-N5kdAF056zw-T3epvTB:-N5kdAF056zw-T3epvTC:bm7dlrh) ([raw file](https://github.com/yiminlin-tri/drake/blob/bc6078dd80f9ef989266022bd20714b06adf677c/multibody/fem/mpm-dev/MPMDriver.cc#L80)):*
> ```cpp
>     for (int p = 0; p < num_samples; ++p) {
>         const Vector3<double>& xp_ref = particles_sample_positions[p];
>         SpatialVelocity<double> v_ref = init_v.Shift(xp_ref);
> ```

We need to be extra careful here with frames. This is a common source of error.

If `init_v` measured and expressed in the world frame , then you would need to shift by `p_BoBp_W` the displacement from the center of the object to the particle's position expressed in the world frame to get the `V_WBp`, the spatial velocity of the particle expressed and measured in the world frame. 

As written right now, it's not clear to me that this is correct. (Not saying this is necessarily wrong though. Just not clear).

**Review by yiminlin-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/22)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 80 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/22#-N5kdAF056zw-T3epvTB:-N5lLB6r4kuj9w-3k6OP:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/bc6078dd80f9ef989266022bd20714b06adf677c/multibody/fem/mpm-dev/MPMDriver.cc#L80)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

We need to be extra careful here with frames. This is a common source of error.

If `init_v` measured and expressed in the world frame , then you would need to shift by `p_BoBp_W` the displacement from the center of the object to the particle's position expressed in the world frame to get the `V_WBp`, the spatial velocity of the particle expressed and measured in the world frame. 

As written right now, it's not clear to me that this is correct. (Not saying this is necessarily wrong though. Just not clear).
</blockquote></details>

Done.

**Review by xuchen-han — COMMENTED** [review]
:lgtm: with two requested TODOs.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/22#-:-N5lXzku0g-qyW-imgCN:b-tf46dq)* status: all files reviewed, 1 unresolved discussion (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 80 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/22#-N5kdAF056zw-T3epvTB:-N5lVa933fDa0txq1-Q8:bdxof2) ([raw file](https://github.com/yiminlin-tri/drake/blob/bc6078dd80f9ef989266022bd20714b06adf677c/multibody/fem/mpm-dev/MPMDriver.cc#L80)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Very nice! The reason I was confused earlier before is because I mistook 

`particles_sample_positions[p]` as `p_BoBp_W` whereas it's in fact `p_BoBp_B`. The new version is much clearer, thanks!

However, it seems like there's no unit test covering these code. Can we at least place a TODO here to acknowledge the fact?
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 102 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/22#-N5lX_WiEiC4Go8L4vp8:-N5lX_WiEiC4Go8L4vp9:bmi30bv) ([raw file](https://github.com/yiminlin-tri/drake/blob/0090380a3f99ea2a78550f03bb0e944ed7ed02cd/multibody/fem/mpm-dev/MPMDriver.cc#L102)):*
> ```cpp
>         // If the particle is in the level set
>         if (level_set.InInterior(p_BoBp_B)) {
>             particles_velocities.emplace_back(V_WBp.translational());
> ```

It just occurs to me that perhaps it makes sense to initialize the Cp matrix according to the rotational part of V_WBp? Could you make a TODO here for us to revisit this in the future?

**Review by yiminlin-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/22#-:-N5ljHlF0s1zt_uJIi_W:bnfp4nl)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 80 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/22#-N5kdAF056zw-T3epvTB:-N5lhCxj5qQwTg-p_C6j:bk8zsms) ([raw file](https://github.com/yiminlin-tri/drake/blob/bc6078dd80f9ef989266022bd20714b06adf677c/multibody/fem/mpm-dev/MPMDriver.cc#L80)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Very nice! The reason I was confused earlier before is because I mistook 

`particles_sample_positions[p]` as `p_BoBp_W` whereas it's in fact `p_BoBp_B`. The new version is much clearer, thanks!

However, it seems like there's no unit test covering these code. Can we at least place a TODO here to acknowledge the fact?
</blockquote></details>

Done. Sounds good! After finishing all the implementations (after plasticity) I will work on some integration tests.

**Review by yiminlin-tri — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/22)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)

**Pull request merged**
