### PR TITLE
A Grid class to hold grid point states

### PR DESCRIPTION
**Pull request by yiminlin-tri**
A simple grid class using structure of arrays design, with simple getters, setters and lexicographical ordering on 3D index.

---
This change is [Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/6)

### CODE REVIEW

**Comment by xuchen-han** [comment]
+@xuchenhan-tri

**Review by xuchen-han — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/6)* status: all files reviewed, 7 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/Grid.h` line 12 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/6#-N2TPpo9-s1Sm1kmHOdR:-N2TPpo9-s1Sm1kmHOdS:b2ni8l0) ([raw file](https://github.com/yiminlin-tri/drake/blob/9502745609a9bf80ccd372b0b4216d409293a566/multibody/fem/mpm-dev/Grid.h#L12)):*
> ```objc
> namespace mpm {
> 
> // A particles class holding vectors of particles' state. The grid can be
> ```

nit



_Suggestion:_
```objc
// A grid class holding vectors of grid states. The grid can be
```
___
*[`multibody/fem/mpm-dev/Grid.h` line 32 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/6#-N2TRBxT5UJ3O4VXPfKc:-N2TRBxT5UJ3O4VXPfKd:b-yfh7wx) ([raw file](https://github.com/yiminlin-tri/drake/blob/9502745609a9bf80ccd372b0b4216d409293a566/multibody/fem/mpm-dev/Grid.h#L32)):*
> ```objc
> // Since we assume an uniform grid, the distance between neighboring gird points
> // are all h. The bottom_corner is the grid node with the smallest (x, y, z)
> // values. We adopt the lexicographical ordering the the grid nodes, where
> ```

BTW, lexicographical ordering is not usually the most memory friendly. See the discussion in https://orionquest.github.io/papers/SSPGASS/paper.html for example.
(I'm not advocating for a more sophisticated ordering now. Just FYI).
___
*[`multibody/fem/mpm-dev/Grid.h` line 41 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/6#-N2TRkHXBe-RHKspEl6S:-N2TRkHXBe-RHKspEl6T:b8d66gk) ([raw file](https://github.com/yiminlin-tri/drake/blob/9502745609a9bf80ccd372b0b4216d409293a566/multibody/fem/mpm-dev/Grid.h#L41)):*
> ```objc
>  public:
>     Grid();
>     Grid(const Vector3<int>& num_gridpt_1D, double h,
> ```

nit, it's not immediately clear what `num_gridpt_1D` does. This deserves some documentation.
___
*[`multibody/fem/mpm-dev/Grid.h` line 49 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/6#-N2TU7DpANZ0nGmO9XFE:-N2TU7DpANZ0nGmO9XFF:b-6slbcc) ([raw file](https://github.com/yiminlin-tri/drake/blob/9502745609a9bf80ccd372b0b4216d409293a566/multibody/fem/mpm-dev/Grid.h#L49)):*
> ```objc
>     const Vector3<double>& get_bottom_corner_position() const;
> 
>     const Vector3<double>& get_position(int i, int j, int k) const;
> ```

It's important to document how i,j,k are used here. Without looking at the code, I expected (i,j,k) corresponds to the grid node with position (i*h, j*h, k*h) whereas in fact i,j,k indexes the offset from the pre-defined "bottom corner".

I think I still prefer the semantic I proposed above because that would make translating between particle positions to grid index easy. Suppose we have a particle at (x,y,z), then the base grid index would simply be (i,j,k) = (round(x/h), round(y/h), round(z/h))
___
*[`multibody/fem/mpm-dev/Grid.h` line 60 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/6#-N2TRvKV0_QEXt-S1Saj:-N2TRvKV0_QEXt-S1Sak:b-uhhjtj) ([raw file](https://github.com/yiminlin-tri/drake/blob/9502745609a9bf80ccd372b0b4216d409293a566/multibody/fem/mpm-dev/Grid.h#L60)):*
> ```objc
> 
>  private:
>     int reduce3DIndex(int i, int j, int k) const;
> ```

nit, it's not immediately clear what this function does. This deserves some documentation. Also reduce3DIndex->Reduce3DIndex.
___
*[`multibody/fem/mpm-dev/Grid.cc` line 7 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/6#-N2TSxc06JNk218uFZ2O:-N2TSxc06JNk218uFZ2P:b1mrxo) ([raw file](https://github.com/yiminlin-tri/drake/blob/9502745609a9bf80ccd372b0b4216d409293a566/multibody/fem/mpm-dev/Grid.cc#L7)):*
> ```cpp
> namespace mpm {
> 
> constexpr double kEps = 4.0 * std::numeric_limits<double>::epsilon();
> ```

nit unused.
___
*[`multibody/fem/mpm-dev/Grid.cc` line 9 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/6#-N2TS6EY0R6zJMf-r-mE:-N2TS6EY0R6zJMf-r-mF:bka8oqm) ([raw file](https://github.com/yiminlin-tri/drake/blob/9502745609a9bf80ccd372b0b4216d409293a566/multibody/fem/mpm-dev/Grid.cc#L9)):*
> ```cpp
> constexpr double kEps = 4.0 * std::numeric_limits<double>::epsilon();
> 
> Grid::Grid(): num_gridpt_(0), num_gridpt_1D_(0, 0, 0), h_(1.0) {}
> ```

I don'q quite see the usefulness of the default constructor. The grid is initialized to empty and can't be modified. 
___
*[`multibody/fem/mpm-dev/Grid.cc` line 32 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/6#-N2TTCTYDj_znBZAoiW2:-N2TTCTYDj_znBZAoiW3:b-beqocu) ([raw file](https://github.com/yiminlin-tri/drake/blob/9502745609a9bf80ccd372b0b4216d409293a566/multibody/fem/mpm-dev/Grid.cc#L32)):*
> ```cpp
>     for (int i = 0; i < num_gridpt_1D_(0); ++i) {
>         idx = reduce3DIndex(i, j, k);
>         positions_[idx] = bottom_corner_position_
> ```

I'm not sure how I feel about this. This leaves the user ability to create two grids with the same `h` but are not "in-sync" (i.e. there exists an offset between the two grids). This problem goes away if we specify the bottom corner's index instead of positions. 
___
*[`multibody/fem/mpm-dev/Grid.cc` line 102 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/6#-N2TQr1m2OJ2Aq5DFZmO:-N2TQr1m2OJ2Aq5DFZmP:bz873hs) ([raw file](https://github.com/yiminlin-tri/drake/blob/9502745609a9bf80ccd372b0b4216d409293a566/multibody/fem/mpm-dev/Grid.cc#L102)):*
> ```cpp
> 
> void Grid::check_3D_index(int i, int j, int k) const {
>     DRAKE_ASSERT(i < num_gridpt_1D_(0));
> ```

FYI, `DRAKE_ASSERT` is only turned on in debug mode. In release mode, this is a no-op.

**Review by yiminlin-tri — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/6#-:-N2ThLVt9TU8_OeGUaTH:bb6un1j)* status: all files reviewed, 3 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/Grid.h` line 49 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/6#-N2TU7DpANZ0nGmO9XFE:-N2Tj5EWAcFjDefKHf8C:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/9502745609a9bf80ccd372b0b4216d409293a566/multibody/fem/mpm-dev/Grid.h#L49)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

It's important to document how i,j,k are used here. Without looking at the code, I expected (i,j,k) corresponds to the grid node with position (i*h, j*h, k*h) whereas in fact i,j,k indexes the offset from the pre-defined "bottom corner".

I think I still prefer the semantic I proposed above because that would make translating between particle positions to grid index easy. Suppose we have a particle at (x,y,z), then the base grid index would simply be (i,j,k) = (round(x/h), round(y/h), round(z/h))
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/Grid.cc` line 9 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/6#-N2TS6EY0R6zJMf-r-mE:-N2Tpoe29_u8YHeyi_5Z:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/9502745609a9bf80ccd372b0b4216d409293a566/multibody/fem/mpm-dev/Grid.cc#L9)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I don'q quite see the usefulness of the default constructor. The grid is initialized to empty and can't be modified. 
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/Grid.cc` line 32 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/6#-N2TTCTYDj_znBZAoiW2:-N2Tpq5i0szZHn1CAu5D:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/9502745609a9bf80ccd372b0b4216d409293a566/multibody/fem/mpm-dev/Grid.cc#L32)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I'm not sure how I feel about this. This leaves the user ability to create two grids with the same `h` but are not "in-sync" (i.e. there exists an offset between the two grids). This problem goes away if we specify the bottom corner's index instead of positions. 
</blockquote></details>

Done.

**Review by xuchen-han — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)

**Pull request merged**
