### PR TITLE
Quadratic B-spline Implementation

### PR DESCRIPTION
**Pull request by yiminlin-tri**
A quadratic B-spline implementation with quick tests using the partition of unity property. 
TODO: 
1. Class design choice is still arbitrary and need to be discussed.
2. Some bad allocations.
3. Test with other grid size.
4. Refactor some routines that maybe useful in the future.

This change is [Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/3)

### CODE REVIEW

**Review by xuchen-han — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/3)* status: 1 of 3 files reviewed, 9 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/main.cpp` line 5 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2JOi-f1CBkzMnzdGEf:-N2JOi-f1CBkzMnzdGEg:b-er1dhf) ([raw file](https://github.com/yiminlin-tri/drake/blob/d990d84bcf4076cde88413bbee54ddc7f3eeaa79/multibody/fem/mpm-dev/main.cpp#L5)):*
> ```cpp
> 
> #include "drake/common/eigen_types.h"
> ```

nit, you should put everything inside
```
namespace drake {
namespace multibody {
namespace mpm {}
}
}
``` 
so that we don't pollute global namespace.
___
*[`multibody/fem/mpm-dev/main.cpp` line 10 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2JP2Ab6ZlMMkCPBpmi:-N2JP2Ab6ZlMMkCPBpmj:b-c14jzq) ([raw file](https://github.com/yiminlin-tri/drake/blob/d990d84bcf4076cde88413bbee54ddc7f3eeaa79/multibody/fem/mpm-dev/main.cpp#L10)):*
> ```cpp
> // TODO(yiminlin.tri): Refactor, helper function to evaluate 1D quadratic spline
> // Reference element: r \in [-1.5, 1.5]
> double eval_1D_basis(double r) {
> ```

BTW, we usually use upper case for function names and class names

e.g. Eval1DBasis(), class Particle, 

and snake cases for functions that are fast 

e.g. get_mass()

and lower case for variable names.
___
*[`multibody/fem/mpm-dev/main.cpp` line 15 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2JPdh-6G825WF7iBm1:-N2JPdh-6G825WF7iBm2:b-ugevfg) ([raw file](https://github.com/yiminlin-tri/drake/blob/d990d84bcf4076cde88413bbee54ddc7f3eeaa79/multibody/fem/mpm-dev/main.cpp#L15)):*
> ```cpp
>         return 0.0;
>     } else if (r_abs < 1.5 && r_abs >= 0.5) {
>         return .5*std::pow(1.5-r_abs, 2);
> ```

Do we suffer performance-wise to use std::pow? 
___
*[`multibody/fem/mpm-dev/main.cpp` line 21 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2JX9yO-1a3AkTKpBkP:-N2JX9yO-1a3AkTKpBkQ:b-yfg3sq) ([raw file](https://github.com/yiminlin-tri/drake/blob/d990d84bcf4076cde88413bbee54ddc7f3eeaa79/multibody/fem/mpm-dev/main.cpp#L21)):*
> ```cpp
> }
> 
> class Particle {
> ```

We should put each class in its own header and implementation file. Otherwise this main.cpp will soon be unreadable and takes forever to compile.
___
*[`multibody/fem/mpm-dev/main.cpp` line 26 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2JPp4SBWtzbl_adIYM:-N2JPp4SBWtzbl_adIYN:b7z22o9) ([raw file](https://github.com/yiminlin-tri/drake/blob/d990d84bcf4076cde88413bbee54ddc7f3eeaa79/multibody/fem/mpm-dev/main.cpp#L26)):*
> ```cpp
>     Particle(double m, double x, double y, double z,
>                        double u1, double u2, double u3) {
>         mass_     = m;
> ```

nit, this can be 

```
    Particle(double m, double x, double y, double z,
                        double u1, double u2, double u3): mass_(m), position_(x,y,z), velocity_(u1,u2,u3){}
```
  
 
___
*[`multibody/fem/mpm-dev/main.cpp` line 44 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2JQnYT8GQNmmUOBZZQ:-N2JQnYT8GQNmmUOBZZR:b-1yumcl) ([raw file](https://github.com/yiminlin-tri/drake/blob/d990d84bcf4076cde88413bbee54ddc7f3eeaa79/multibody/fem/mpm-dev/main.cpp#L44)):*
> ```cpp
> 
>     // TODO(yiminlin.tri):
>     void get_mass(const int& m);
> ```

I suppose you meant set_mass here? Ditto below.

Also, it doesn't make too much sense to set the mass of a particle because the mass never changes.
___
*[`multibody/fem/mpm-dev/main.cpp` line 57 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2JRks-9ruofmHmeoUi:-N2JRks00sTnkhwunKE_:b-mzf42j) ([raw file](https://github.com/yiminlin-tri/drake/blob/d990d84bcf4076cde88413bbee54ddc7f3eeaa79/multibody/fem/mpm-dev/main.cpp#L57)):*
> ```cpp
>  public:
>     // TODO(yiminlin.tri): constructor using Vector3, default constructor
>     GridPoint() {}
> ```

Not sure why we want a default constructor. It would leave the vector data in an unintialized state.
___
*[`multibody/fem/mpm-dev/main.cpp` line 99 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2JUeOSCIi2IRYE5w_J:-N2JUeOSCIi2IRYE5w_K:b34xju3) ([raw file](https://github.com/yiminlin-tri/drake/blob/d990d84bcf4076cde88413bbee54ddc7f3eeaa79/multibody/fem/mpm-dev/main.cpp#L99)):*
> ```cpp
> };
> ```

Can I convince you to use googletest instead of putting all tests in a single file?

It does the expectation checks for us automatically and makes the tests maintainable. 
___
*[`multibody/fem/mpm-dev/main.cpp` line 222 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2JWMSQ5Na1BTQ5XcwK:-N2JWMSQ5Na1BTQ5XcwL:b-qddggh) ([raw file](https://github.com/yiminlin-tri/drake/blob/d990d84bcf4076cde88413bbee54ddc7f3eeaa79/multibody/fem/mpm-dev/main.cpp#L222)):*
> ```cpp
>     for (zi = -1.0; zi <= 1.0; zi += 0.2) {
>     for (yi = -1.0; yi <= 1.0; yi += 0.2) {
>     for (xi = -1.0; xi <= 1.0; xi += 0.2) {
> ```

What is 0.2 here? Shouldn't we increment by h instead?
___
*[`multibody/fem/mpm-dev/main.cpp` line 228 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2JWaU_ErcKIKZMBSXq:-N2JWaU_ErcKIKZMBSXr:bgketin) ([raw file](https://github.com/yiminlin-tri/drake/blob/d990d84bcf4076cde88413bbee54ddc7f3eeaa79/multibody/fem/mpm-dev/main.cpp#L228)):*
> ```cpp
>         tmpvec3 = {xi, yi, zi};
>         for (int idx = 0; idx < 125; ++idx) {
>             i = idx % 5;
> ```

nit Remove unused variables.

**Review by xuchen-han — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/3)* status: all files reviewed, 9 unresolved discussions (waiting on @yiminlin-tri)

**Review by yiminlin-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/3)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/main.cpp` line 5 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2JOi-f1CBkzMnzdGEf:-N2OV90kC1J3RriYcbX-:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/d990d84bcf4076cde88413bbee54ddc7f3eeaa79/multibody/fem/mpm-dev/main.cpp#L5)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, you should put everything inside
```
namespace drake {
namespace multibody {
namespace mpm {}
}
}
``` 
so that we don't pollute global namespace.

</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/main.cpp` line 10 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2JP2Ab6ZlMMkCPBpmi:-N2OVOq2Av0-myMNPbba:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/d990d84bcf4076cde88413bbee54ddc7f3eeaa79/multibody/fem/mpm-dev/main.cpp#L10)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, we usually use upper case for function names and class names

e.g. Eval1DBasis(), class Particle, 

and snake cases for functions that are fast 

e.g. get_mass()

and lower case for variable names.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/main.cpp` line 15 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2JPdh-6G825WF7iBm1:-N2OW6k35QHdHgC6kyDL:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/d990d84bcf4076cde88413bbee54ddc7f3eeaa79/multibody/fem/mpm-dev/main.cpp#L15)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Do we suffer performance-wise to use std::pow? 
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/main.cpp` line 21 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2JX9yO-1a3AkTKpBkP:-N2OW8vVBKOtGlH87cqm:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/d990d84bcf4076cde88413bbee54ddc7f3eeaa79/multibody/fem/mpm-dev/main.cpp#L21)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

We should put each class in its own header and implementation file. Otherwise this main.cpp will soon be unreadable and takes forever to compile.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/main.cpp` line 26 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2JPp4SBWtzbl_adIYM:-N2OWAEfDrLaQtZMXa6E:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/d990d84bcf4076cde88413bbee54ddc7f3eeaa79/multibody/fem/mpm-dev/main.cpp#L26)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, this can be 

```
    Particle(double m, double x, double y, double z,
                        double u1, double u2, double u3): mass_(m), position_(x,y,z), velocity_(u1,u2,u3){}
```
  
 


</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/main.cpp` line 44 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2JQnYT8GQNmmUOBZZQ:-N2OWCMBCJBOAIDVNtPU:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/d990d84bcf4076cde88413bbee54ddc7f3eeaa79/multibody/fem/mpm-dev/main.cpp#L44)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I suppose you meant set_mass here? Ditto below.

Also, it doesn't make too much sense to set the mass of a particle because the mass never changes.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/main.cpp` line 57 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2JRks-9ruofmHmeoUi:-N2OWF42Aq6VLFF32v3X:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/d990d84bcf4076cde88413bbee54ddc7f3eeaa79/multibody/fem/mpm-dev/main.cpp#L57)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Not sure why we want a default constructor. It would leave the vector data in an unintialized state.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/main.cpp` line 99 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2JUeOSCIi2IRYE5w_J:-N2OWGTL-9O_iR4mbjA5:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/d990d84bcf4076cde88413bbee54ddc7f3eeaa79/multibody/fem/mpm-dev/main.cpp#L99)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Can I convince you to use googletest instead of putting all tests in a single file?

It does the expectation checks for us automatically and makes the tests maintainable. 
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/main.cpp` line 222 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2JWMSQ5Na1BTQ5XcwK:-N2OWHmjAxOj-5gDURVw:bl8v3by) ([raw file](https://github.com/yiminlin-tri/drake/blob/d990d84bcf4076cde88413bbee54ddc7f3eeaa79/multibody/fem/mpm-dev/main.cpp#L222)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

What is 0.2 here? Shouldn't we increment by h instead?
</blockquote></details>

As discussed, 0.2 is the interval of sampling points. The sampled points are used to check the partition of unity property and it is different from the grid point we are trying to use. 
___
*[`multibody/fem/mpm-dev/main.cpp` line 228 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2JWaU_ErcKIKZMBSXq:-N2OWZNnBPETRE4z-n3n:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/d990d84bcf4076cde88413bbee54ddc7f3eeaa79/multibody/fem/mpm-dev/main.cpp#L228)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit Remove unused variables. 
</blockquote></details>

Done

**Review by xuchen-han — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/3#-:-N2OZaOuBLWL1qRMoLnW:bnfp4nl)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/BSpline.h` line 16 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2OXAJjBxxEYjbGPJvq:-N2OXAJkAmH66ryNZ9WW:b819igt) ([raw file](https://github.com/yiminlin-tri/drake/blob/2712bf72eb4b633c7c64ccf6a3eabcda1bdf3f39/multibody/fem/mpm-dev/BSpline.h#L16)):*
> ```objc
> 
>     // Check whether the input point is inside the support of this Bspline
>     bool inSupport(const Vector3<double>& x);
> ```

BTW, we usually write this as `InSupport` instead of `inSupport`.
___
*[`multibody/fem/mpm-dev/main.cpp` line 10 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2JP2Ab6ZlMMkCPBpmi:-N2OYir31Lgs9GyNsL65:bufnies) ([raw file](https://github.com/yiminlin-tri/drake/blob/d990d84bcf4076cde88413bbee54ddc7f3eeaa79/multibody/fem/mpm-dev/main.cpp#L10)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Done
</blockquote></details>

eval1DBasis->Eval1DBasis
___
*[`multibody/fem/mpm-dev/test/BSpline_test.cc` line 160 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2OZQqy69MUVLNEv_6B:-N2OZQqy69MUVLNEv_6C:bx21mau) ([raw file](https://github.com/yiminlin-tri/drake/blob/2712bf72eb4b633c7c64ccf6a3eabcda1bdf3f39/multibody/fem/mpm-dev/test/BSpline_test.cc#L160)):*
> ```cpp
> 
>         ASSERT_TRUE(std::abs(sum_sample-1.0)
>                     < std::numeric_limits<float>::epsilon());
> ```

float->double?
___
*[`multibody/fem/mpm-dev/test/BSpline_test.cc` line 218 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2OZMT-Ausg1Jjtp7mn:-N2OZMT04gYp3OqMzgHk:bx21mau) ([raw file](https://github.com/yiminlin-tri/drake/blob/2712bf72eb4b633c7c64ccf6a3eabcda1bdf3f39/multibody/fem/mpm-dev/test/BSpline_test.cc#L218)):*
> ```cpp
> 
>         ASSERT_TRUE(std::abs(sum_sample-1.0)
>                     < std::numeric_limits<float>::epsilon());
> ```

float->double?

**Review by xuchen-han — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/3)* status: all files reviewed, 2 unresolved discussions (waiting on @yiminlin-tri)

**Review by yiminlin-tri — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/3#-:-N2OanVFEQei6IV1F7yz:b-ucfknh)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/BSpline.h` line 16 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2OXAJjBxxEYjbGPJvq:-N2O_kKf9qDi2lQ9HNsm:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/2712bf72eb4b633c7c64ccf6a3eabcda1bdf3f39/multibody/fem/mpm-dev/BSpline.h#L16)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, we usually write this as `InSupport` instead of `inSupport`.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/main.cpp` line 10 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2JP2Ab6ZlMMkCPBpmi:-N2Oalg60s1vk4AP5FWl:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/d990d84bcf4076cde88413bbee54ddc7f3eeaa79/multibody/fem/mpm-dev/main.cpp#L10)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

eval1DBasis->Eval1DBasis
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/BSpline_test.cc` line 160 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2OZQqy69MUVLNEv_6B:-N2OajKl7av0evcKugge:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/2712bf72eb4b633c7c64ccf6a3eabcda1bdf3f39/multibody/fem/mpm-dev/test/BSpline_test.cc#L160)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

float->double?
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/BSpline_test.cc` line 218 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/3#-N2OZMT-Ausg1Jjtp7mn:-N2Oak1uBuZy39K2zcKC:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/2712bf72eb4b633c7c64ccf6a3eabcda1bdf3f39/multibody/fem/mpm-dev/test/BSpline_test.cc#L218)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

float->double?
</blockquote></details>

Done

**Review by yiminlin-tri — COMMENTED** [review]
> Reviewed 5 of 6 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)

**Pull request merged**
