### PR TITLE
MPM particle+grid advection and stress update

### PR DESCRIPTION
**Pull request by yiminlin-tri**
This change is [Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/13)

### CODE REVIEW

**Review by yiminlin-tri — COMMENTED** [review]
@xuchenhan-tri Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/13#-:-N3S4mfYA-KmxzqBAU0f:b7am51h)* status: 0 of 12 files reviewed, all discussions resolved

**Review by yiminlin-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/13)* status: 0 of 12 files reviewed, 1 unresolved discussion

___
*[`multibody/fem/mpm-dev/Grid.h` line 100 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3V1zYb41zf3quJ83ms:-N3V1zYb41zf3quJ83mt:b-wivk7s) ([raw file](https://github.com/yiminlin-tri/drake/blob/1edf3360c0f74c07990d509b4c5a06fe3cb5d3ca/multibody/fem/mpm-dev/Grid.h#L100)):*
> ```objc
>     // the member variable, we update the velocity with the formula
>     // v^{n+1} = v^n + dt*f^n/m^n
>     void UpdateVelocity(double dt);
> ```

I am thinking maybe it is a good idea to pass in a flag to indicate whether we want to add gravitational force here. What do you think?

**Review by xuchen-han — CHANGES_REQUESTED** [review]
I think I reviewed everything, but there's quite a bit of duplication between this PR and the previous one. I'll wait till the rebase to make another pass.

BTW use +@xuchenhan-tri so that it pops up a bit more on my dashboard.

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/13#-:-N3V8TsZ568CsIA_naBD:b-yvoy2c)* status: 0 of 12 files reviewed, 7 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/Grid.h` line 100 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3V1zYb41zf3quJ83ms:-N3VCq7A7mcFaFR--zgp:b-86stqi) ([raw file](https://github.com/yiminlin-tri/drake/blob/1edf3360c0f74c07990d509b4c5a06fe3cb5d3ca/multibody/fem/mpm-dev/Grid.h#L100)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

I am thinking maybe it is a good idea to pass in a flag to indicate whether we want to add gravitational force here. What do you think?
</blockquote></details>

I see a few options. 
1. Have the Grid class store a gravity vector with corresponding setters and getters. The gravity is always applied. If not desired, set it to zero.
2. Pass in a gravity vector to the UpdateVelocity function.
3. Set another class that handles external velocity field with a function `void ApplyExternalVelocity(Grid*) const;`
___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 118 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3V9ibDEVpVxLLlaTJb:-N3V9ibDEVpVxLLlaTJc:b-rjbmqg) ([raw file](https://github.com/yiminlin-tri/drake/blob/1edf3360c0f74c07990d509b4c5a06fe3cb5d3ca/multibody/fem/mpm-dev/MPMTransfer.h#L118)):*
> ```objc
> 
>     // Update particle states F_p^{n+1} and v_p^{n+1}
>     void UpdateParticleStates(const std::array<Vector3<double>, 27>&
> ```

With the new function `UpdateKirchoffStress` which also updates the particle states, the naming of this function becomes a bit ambiguous. How about `WriteBatchStateToParticles` instead?
___
*[`multibody/fem/mpm-dev/Particles.h` line 74 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3VA4KO4Y9Mz5v-Kjx9:-N3VA4KO4Y9Mz5v-KjxA:blfni2v) ([raw file](https://github.com/yiminlin-tri/drake/blob/1edf3360c0f74c07990d509b4c5a06fe3cb5d3ca/multibody/fem/mpm-dev/Particles.h#L74)):*
> ```objc
>     // Assume the deformation gradient is updated, update Kirchhoff stress tau
>     // given the constitutive relation
>     void UpdateKirchhoffStresses(const CorotatedModel& corotated_model);
> ```

nit There should probably be a TODO here to support more constitutive models.

Also BTW, do you have plans about who will own the CorotatedModel?
___
*[`multibody/fem/mpm-dev/test/Grid_test.cc` line 278 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3VB1WhBqYsOJMKoJh0:-N3VB1WhBqYsOJMKoJh1:b6lkwqk) ([raw file](https://github.com/yiminlin-tri/drake/blob/1edf3360c0f74c07990d509b4c5a06fe3cb5d3ca/multibody/fem/mpm-dev/test/Grid_test.cc#L278)):*
> ```cpp
>         tmpscaling = 1.2*k + 0.3*j + i;
>         EXPECT_TRUE(CompareMatrices(grid.get_velocity(i, j, k),
>             Vector3<double>(tmpscaling-0.2, -tmpscaling+0.2, tmpscaling-0.2),
> ```

nit It's usually brittle to hard code like this -- when someone messes changes dt to 0.3 for whatever reason, the test fails.
___
*[`multibody/fem/mpm-dev/test/Particles_test.cc` line 15 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3VBOnuC_3vGoF-9r4l:-N3VBOnv3Srk65XuUT2j:byw212a) ([raw file](https://github.com/yiminlin-tri/drake/blob/1edf3360c0f74c07990d509b4c5a06fe3cb5d3ca/multibody/fem/mpm-dev/test/Particles_test.cc#L15)):*
> ```cpp
> namespace {
> 
> constexpr double pi = 3.14159265358979323846;
> ```

FYI If you `#include <math.h>` you could use `M_PI` for the constant.
___
*[`multibody/fem/mpm-dev/test/Particles_test.cc` line 17 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3VBUi2EFqxCDy67QDz:-N3VBUi2EFqxCDy67QE-:btvg99x) ([raw file](https://github.com/yiminlin-tri/drake/blob/1edf3360c0f74c07990d509b4c5a06fe3cb5d3ca/multibody/fem/mpm-dev/test/Particles_test.cc#L17)):*
> ```cpp
> constexpr double pi = 3.14159265358979323846;
> constexpr double kEps = 1e-14;
> constexpr double TOLERANCE = 1e-10;
> ```

nit why do we need two different tolerances?
___
*[`multibody/fem/mpm-dev/test/Particles_test.cc` line 300 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3VBt7Z8uaoM56ZuxrA:-N3VBt7Z8uaoM56ZuxrB:b1mry5) ([raw file](https://github.com/yiminlin-tri/drake/blob/1edf3360c0f74c07990d509b4c5a06fe3cb5d3ca/multibody/fem/mpm-dev/test/Particles_test.cc#L300)):*
> ```cpp
> 
> GTEST_TEST(ParticlesClassTest, TestAdvectAndUpdateKirchhoffStress) {
>     std::vector<Vector3<double>> positions;
> ```

nit unused?
___
*[`multibody/fem/mpm-dev/test/Particles_test.cc` line 347 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3VC0vJ2Od5tml9d69f:-N3VC0vJ2Od5tml9d69g:b-n4g4z8) ([raw file](https://github.com/yiminlin-tri/drake/blob/1edf3360c0f74c07990d509b4c5a06fe3cb5d3ca/multibody/fem/mpm-dev/test/Particles_test.cc#L347)):*
> ```cpp
>                                 Vector3<double>(0.3, 1.4, 5.4), kEps));
> 
>     // Update Kirchhoff stress
> ```

Seems like the Kirchhoff stress test and the advection test are two distinct tests. Can we separate them?

**Review by xuchen-han — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/13)* status: 0 of 21 files reviewed, 8 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`bindings/pydrake/trajectories_py.cc` line 203 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3VZxbc8xhV5QzAlfe0:-N3VZxbc8xhV5QzAlfe1:b-g682y8) ([raw file](https://github.com/yiminlin-tri/drake/blob/e9e374be9b36ba8dbe9f727b2e1bac24b9e67c9d/bindings/pydrake/trajectories_py.cc#L203)):*
> ```cpp
>           .def("end_time", overload_cast_explicit<T>(&Class::end_time),
>               cls_doc.end_time.doc)
>           .def("is_time_in_index_range", &Class::is_time_in_index_range, py::arg("t"),
> ```

Quite a bit of supposedly unintended changes. Perhaps some grep mishaps?

**Review by yiminlin-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/13)* status: 0 of 21 files reviewed, 8 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/Grid.h` line 100 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3V1zYb41zf3quJ83ms:-N3VI84KEfPu7D2KMJwr:b16n34l) ([raw file](https://github.com/yiminlin-tri/drake/blob/1edf3360c0f74c07990d509b4c5a06fe3cb5d3ca/multibody/fem/mpm-dev/Grid.h#L100)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I see a few options. 
1. Have the Grid class store a gravity vector with corresponding setters and getters. The gravity is always applied. If not desired, set it to zero.
2. Pass in a gravity vector to the UpdateVelocity function.
3. Set another class that handles external velocity field with a function `void ApplyExternalVelocity(Grid*) const;`
</blockquote></details>

I think I will do the third way, because seems like we want other external forces in the future. I will make a future PR then. Thanks!
___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 118 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3V9ibDEVpVxLLlaTJb:-N3VJ11L0zL1VH320lhN:bt25e88) ([raw file](https://github.com/yiminlin-tri/drake/blob/1edf3360c0f74c07990d509b4c5a06fe3cb5d3ca/multibody/fem/mpm-dev/MPMTransfer.h#L118)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

With the new function `UpdateKirchoffStress` which also updates the particle states, the naming of this function becomes a bit ambiguous. How about `WriteBatchStateToParticles` instead?
</blockquote></details>

Done. Looks great
___
*[`multibody/fem/mpm-dev/Particles.h` line 74 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3VA4KO4Y9Mz5v-Kjx9:-N3VJIHt4jI_qbMRX13e:b-20foaf) ([raw file](https://github.com/yiminlin-tri/drake/blob/1edf3360c0f74c07990d509b4c5a06fe3cb5d3ca/multibody/fem/mpm-dev/Particles.h#L74)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit There should probably be a TODO here to support more constitutive models.

Also BTW, do you have plans about who will own the CorotatedModel?
</blockquote></details>

The driver class will own it. The driver class will own Particles, Grid, and a CorotatedModel. Another option will be put CorotatedModel directly into Particles as a member when we constructed the Particles. But I am thinking we may use CorotatedModel at the grid level or for other calculations, so make it a separate object and put it in the driver class maybe better?
___
*[`bindings/pydrake/trajectories_py.cc` line 203 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3VZxbc8xhV5QzAlfe0:-N3V_KEq03fG9oo0v6Xe:bq55pw2) ([raw file](https://github.com/yiminlin-tri/drake/blob/e9e374be9b36ba8dbe9f727b2e1bac24b9e67c9d/bindings/pydrake/trajectories_py.cc#L203)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Quite a bit of supposedly unintended changes. Perhaps some grep mishaps? 
</blockquote></details>

Done. Oops...

**Review by xuchen-han — COMMENTED** [review]
> Reviewed 8 of 12 files at r1, 1 of 12 files at r2, 9 of 9 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/13)* status: all files reviewed, 6 unresolved discussions (waiting on @yiminlin-tri)

___
*[`bindings/pydrake/systems/jupyter_widgets_examples.ipynb` line 169 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3VbCY2-pc2wK3cZ8cR:-N3VbCY2-pc2wK3cZ8cS:b9ohh3o) ([raw file](https://github.com/yiminlin-tri/drake/blob/2b1aded369621ed88e36b65feca9d27dcb4d7bfe/bindings/pydrake/systems/jupyter_widgets_examples.ipynb#L169)):*
> ```
>  "nbformat": 4,
>  "nbformat_minor": 4
> }
> ```

nit one more file to be reverted.
___
*[`multibody/fem/mpm-dev/Particles.h` line 74 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3VA4KO4Y9Mz5v-Kjx9:-N3VfWnPE4DR6uq5HbCu:binp0r2) ([raw file](https://github.com/yiminlin-tri/drake/blob/1edf3360c0f74c07990d509b4c5a06fe3cb5d3ca/multibody/fem/mpm-dev/Particles.h#L74)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

The driver class will own it. The driver class will own Particles, Grid, and a CorotatedModel. Another option will be put CorotatedModel directly into Particles as a member when we constructed the Particles. But I am thinking we may use CorotatedModel at the grid level or for other calculations, so make it a separate object and put it in the driver class maybe better?
</blockquote></details>

I think both will be ok for our purpose. 

But it may be beneficial to think about these things in advance. (e.g. what if we want two different types of constitutive relationships, one for a group of particles and one for another. That kind of things).

**Review by yiminlin-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/13)* status: all files reviewed, 5 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/Particles.h` line 74 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3VA4KO4Y9Mz5v-Kjx9:-N3VquR18MbLyFIGJwzS:boea0tt) ([raw file](https://github.com/yiminlin-tri/drake/blob/1edf3360c0f74c07990d509b4c5a06fe3cb5d3ca/multibody/fem/mpm-dev/Particles.h#L74)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I think both will be ok for our purpose. 

But it may be beneficial to think about these things in advance. (e.g. what if we want two different types of constitutive relationships, one for a group of particles and one for another. That kind of things).
</blockquote></details>

Thanks for the advice!

**Review by yiminlin-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/13)* status: 17 of 36 files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/test/Grid_test.cc` line 278 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3VB1WhBqYsOJMKoJh0:-N3VuE2L4lCKIsgYC1Eg:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/1edf3360c0f74c07990d509b4c5a06fe3cb5d3ca/multibody/fem/mpm-dev/test/Grid_test.cc#L278)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit It's usually brittle to hard code like this -- when someone messes changes dt to 0.3 for whatever reason, the test fails.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/Particles_test.cc` line 15 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3VBOnuC_3vGoF-9r4l:-N3VrP4p9slj9F0cwB82:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/1edf3360c0f74c07990d509b4c5a06fe3cb5d3ca/multibody/fem/mpm-dev/test/Particles_test.cc#L15)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

FYI If you `#include <math.h>` you could use `M_PI` for the constant.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/Particles_test.cc` line 17 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3VBUi2EFqxCDy67QDz:-N3VrNYjCqocrwOa74Pr:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/1edf3360c0f74c07990d509b4c5a06fe3cb5d3ca/multibody/fem/mpm-dev/test/Particles_test.cc#L17)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit why do we need two different tolerances?
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/Particles_test.cc` line 300 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3VBt7Z8uaoM56ZuxrA:-N3VrxK5DAThmNU1zzAw:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/1edf3360c0f74c07990d509b4c5a06fe3cb5d3ca/multibody/fem/mpm-dev/test/Particles_test.cc#L300)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit unused?
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/Particles_test.cc` line 347 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3VC0vJ2Od5tml9d69f:-N3Vt66x-4Ito5JmEWcn:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/1edf3360c0f74c07990d509b4c5a06fe3cb5d3ca/multibody/fem/mpm-dev/test/Particles_test.cc#L347)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Seems like the Kirchhoff stress test and the advection test are two distinct tests. Can we separate them?
</blockquote></details>

Done
___
*[`bindings/pydrake/systems/jupyter_widgets_examples.ipynb` line 169 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3VbCY2-pc2wK3cZ8cR:-N3VtvEWDAeNPypZzHbu:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/2b1aded369621ed88e36b65feca9d27dcb4d7bfe/bindings/pydrake/systems/jupyter_widgets_examples.ipynb#L169)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit one more file to be reverted.
</blockquote></details>

Done

**Review by xuchen-han — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r8, 4 of 6 files at r9, 5 of 12 files at r15, 7 of 7 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/13)* status: 18 of 27 files reviewed, 5 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 40 at r16](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3WJ4qh0DfU_m6WPLvi:-N3WJ4qh0DfU_m6WPLvj:b632471) ([raw file](https://github.com/yiminlin-tri/drake/blob/88eb9ba498e0a824a0b8a1881c280cb7b7504c75/multibody/fem/mpm-dev/MPMTransfer.h#L40)):*
> ```objc
>                                  Particles* particles);
> 
>     // Transfer velocities on the grids to velocities and deformation
> ```

I missed this in the rebase, please remove.
___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 128 at r16](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3WJEqG3Pvb2bLkcEuU:-N3WJEqG3Pvb2bLkcEuV:b632471) ([raw file](https://github.com/yiminlin-tri/drake/blob/88eb9ba498e0a824a0b8a1881c280cb7b7504c75/multibody/fem/mpm-dev/MPMTransfer.h#L128)):*
> ```objc
>                               Particles* particles);
> 
>     // Update particle states F_p^{n+1} and v_p^{n+1}
> ```

I missed this in the rebase, please remove.
___
*[`multibody/fem/mpm-dev/main.cpp` line 30 at r16](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3WJJxeDtNfMUjsAz9g:-N3WJJxeDtNfMUjsAz9h:b67tt25) ([raw file](https://github.com/yiminlin-tri/drake/blob/88eb9ba498e0a824a0b8a1881c280cb7b7504c75/multibody/fem/mpm-dev/main.cpp#L30)):*
> ```cpp
> int main() {
>     return drake::multibody::mpm::DoMain();
> }
> ```

I missed this in the rebase, please revert.
___
*[`multibody/fem/mpm-dev/test/Grid_test.cc` line 278 at r16](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3WJmCo-ByR8hSURWWf:-N3WJmCo-ByR8hSURWWg:b-bo1yxu) ([raw file](https://github.com/yiminlin-tri/drake/blob/88eb9ba498e0a824a0b8a1881c280cb7b7504c75/multibody/fem/mpm-dev/test/Grid_test.cc#L278)):*
> ```cpp
>         tmpscaling = 1.2*k + 0.3*j + i;
>         EXPECT_TRUE(CompareMatrices(grid.get_velocity(i, j, k),
>             Vector3<double>(tmpscaling-0.2, -tmpscaling+0.2, tmpscaling-0.2),
> ```

0.2->dt.
___
*[`multibody/fem/mpm-dev/test/Particles_test.cc` line 15 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3VBOnuC_3vGoF-9r4l:-N3WJXOD5UDFPDaqmmIc:b-epan2z) ([raw file](https://github.com/yiminlin-tri/drake/blob/1edf3360c0f74c07990d509b4c5a06fe3cb5d3ca/multibody/fem/mpm-dev/test/Particles_test.cc#L15)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Done
</blockquote></details>

This is messed up in the rebase process (probably my bad). Perhaps easiest fix is to manually fix up.
___
*[`multibody/fem/mpm-dev/test/Particles_test.cc` line 300 at r16](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3WJr0h0bqgN71FLJZI:-N3WJr0h0bqgN71FLJZJ:b1mrxo) ([raw file](https://github.com/yiminlin-tri/drake/blob/88eb9ba498e0a824a0b8a1881c280cb7b7504c75/multibody/fem/mpm-dev/test/Particles_test.cc#L300)):*
> ```cpp
> 
> GTEST_TEST(ParticlesClassTest, TestAdvectAndUpdateKirchhoffStress) {
>     std::vector<Vector3<double>> positions;
> ```

nit unused.

**Review by xuchen-han — COMMENTED** [review]
> Reviewed 8 of 9 files at r11, 1 of 3 files at r13.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/13)* status: all files reviewed, 5 unresolved discussions (waiting on @yiminlin-tri)

**Review by yiminlin-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/13)* status: 21 of 27 files reviewed, 4 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 40 at r16](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3WJ4qh0DfU_m6WPLvi:-N3WKAA86vyw1FDQRcvV:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/88eb9ba498e0a824a0b8a1881c280cb7b7504c75/multibody/fem/mpm-dev/MPMTransfer.h#L40)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I missed this in the rebase, please remove.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 128 at r16](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3WJEqG3Pvb2bLkcEuU:-N3WKQ58AoiOcG8LgXP9:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/88eb9ba498e0a824a0b8a1881c280cb7b7504c75/multibody/fem/mpm-dev/MPMTransfer.h#L128)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I missed this in the rebase, please remove.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/main.cpp` line 30 at r16](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3WJJxeDtNfMUjsAz9g:-N3WKU-v3Rsx-9RR_ORq:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/88eb9ba498e0a824a0b8a1881c280cb7b7504c75/multibody/fem/mpm-dev/main.cpp#L30)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I missed this in the rebase, please revert.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/Grid_test.cc` line 278 at r16](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3WJmCo-ByR8hSURWWf:-N3WKYPb0bUHAo8bl7Dz:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/88eb9ba498e0a824a0b8a1881c280cb7b7504c75/multibody/fem/mpm-dev/test/Grid_test.cc#L278)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

0.2->dt.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/Particles_test.cc` line 15 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3VBOnuC_3vGoF-9r4l:-N3WKkqBAj1PDet765qc:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/1edf3360c0f74c07990d509b4c5a06fe3cb5d3ca/multibody/fem/mpm-dev/test/Particles_test.cc#L15)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This is messed up in the rebase process (probably my bad). Perhaps easiest fix is to manually fix up.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/Particles_test.cc` line 300 at r16](https://reviewable.io/reviews/yiminlin-tri/drake/13#-N3WJr0h0bqgN71FLJZI:-N3WMW68CwKV6czT45ut:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/88eb9ba498e0a824a0b8a1881c280cb7b7504c75/multibody/fem/mpm-dev/test/Particles_test.cc#L300)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit unused.
</blockquote></details>

Done

**Review by yiminlin-tri — COMMENTED** [review]
+@xuchenhan-tri Fixed. Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/13#-:-N3WU-mX2KqIywUj3XnG:b-oprljw)* status: 24 of 27 files reviewed, 4 unresolved discussions (waiting on @xuchenhan-tri)

**Review by xuchen-han — APPROVED** [review]
> Reviewed 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)

**Pull request merged**
