### PR TITLE
[mpm-dev] Add APIC (Affine Particle-In-Cell)

### PR DESCRIPTION
**Pull request by yiminlin-tri**
This change is [Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/20)

### CODE REVIEW

**Review by yiminlin-tri — COMMENTED** [review]
+@xuchenhan-tri Added APIC and refactored the test. TODO: PIC doesn't fail for my current test cases... I will open a separate PR imposing initial angular velocity to particles (Currently we only impose uniform linear velocity on particles.)

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/20#-:-N5bFXzmDrwZSbgDpx6r:b-mnn03x)* status: 0 of 15 files reviewed, all discussions resolved (waiting on @xuchenhan-tri)

**Review by xuchen-han — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/20)* status: 2 of 15 files reviewed, 5 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 94 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5bIAXPDjMYd2ApKSnN:-N5bIAXPDjMYd2ApKSnO:b-45nv8g) ([raw file](https://github.com/yiminlin-tri/drake/blob/0061e1617d06c00f41cd926274a778f79d0e35a2/multibody/fem/mpm-dev/MPMDriver.cc#L94)):*
> ```cpp
>         const Vector3<double>& xp = particles_positions[p];
>         particles_.AddParticle(xp, init_v, init_m, reference_volume_p,
>                                Matrix3<double>::Identity(),
> ```

As this list grows, it'd improve readability if we give these arguments names. e.g. 
```particles_.AddParticle(xp, init_v, init_m, reference_volume_p, deformation_gradient, affine_velocity_field);```
___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 55 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5bJUjJ7Ke2iSNL1_Sl:-N5bJUjKBd-6QRXQDYRL:bozar55) ([raw file](https://github.com/yiminlin-tri/drake/blob/0061e1617d06c00f41cd926274a778f79d0e35a2/multibody/fem/mpm-dev/MPMTransfer.h#L55)):*
> ```objc
>     };
> 
>     struct BatchState {
> ```

nit, probably worth mentioning why we want to keep track of both position and velocity.
___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 115 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5bJfHY0rHp519ObT2D:-N5bJfHY0rHp519ObT2E:b-26ipip) ([raw file](https://github.com/yiminlin-tri/drake/blob/0061e1617d06c00f41cd926274a778f79d0e35a2/multibody/fem/mpm-dev/MPMTransfer.h#L115)):*
> ```objc
>                                      double reference_volume_p,
>                                      const Vector3<double>& velocity_p,
>                                      const Matrix3<double>& B_p,
> ```

nit, the parameter `B_p` is obscure enough to deserve some documentation.

Also, can you remind me why we changed `momentum_p` to `velocity_p`? Is it simply a mistake in the previous version?
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 40 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5bKEYM6US6tcYTWPU7:-N5bKEYM6US6tcYTWPU8:bjf8cxu) ([raw file](https://github.com/yiminlin-tri/drake/blob/0061e1617d06c00f41cd926274a778f79d0e35a2/multibody/fem/mpm-dev/MPMTransfer.cc#L40)):*
> ```cpp
>                 AccumulateGridStatesOnBatch(p, mass_p, ref_volume_p,
>                                             particles.get_velocity(p),
>                                             particles.get_affine_matrix(p),
> ```

This looks a little suspicious. It seems like the function parameter takes in the B_p matrix instead of the full affine matrix?
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 270 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5bUmGsAOcg6R3-WUIA:-N5bUmGsAOcg6R3-WUIB:b3vsopf) ([raw file](https://github.com/yiminlin-tri/drake/blob/0061e1617d06c00f41cd926274a778f79d0e35a2/multibody/fem/mpm-dev/MPMTransfer.cc#L270)):*
> ```cpp
>     int idx_local;
>     double Ni_p;
>     Vector3<double> vp_new_i;
> ```

nit, this variable needs some documentation.

**Review by yiminlin-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/20)* status: 2 of 15 files reviewed, 3 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 94 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5bIAXPDjMYd2ApKSnN:-N5c858zD6yupB8kfB2V:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/0061e1617d06c00f41cd926274a778f79d0e35a2/multibody/fem/mpm-dev/MPMDriver.cc#L94)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

As this list grows, it'd improve readability if we give these arguments names. e.g. 
```particles_.AddParticle(xp, init_v, init_m, reference_volume_p, deformation_gradient, affine_velocity_field);```
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 115 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5bJfHY0rHp519ObT2D:-N5f1psv5UVj5UqzrT6n:bx6mrfn) ([raw file](https://github.com/yiminlin-tri/drake/blob/0061e1617d06c00f41cd926274a778f79d0e35a2/multibody/fem/mpm-dev/MPMTransfer.h#L115)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, the parameter `B_p` is obscure enough to deserve some documentation.

Also, can you remind me why we changed `momentum_p` to `velocity_p`? Is it simply a mistake in the previous version?
</blockquote></details>

I passed in velocity because I can reuse m_ip = m_p * w_ip once, so possibly saving one operation...
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 40 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5bKEYM6US6tcYTWPU7:-N5f1J515KaxxRa9lKhx:b-2qmjwq) ([raw file](https://github.com/yiminlin-tri/drake/blob/0061e1617d06c00f41cd926274a778f79d0e35a2/multibody/fem/mpm-dev/MPMTransfer.cc#L40)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This looks a little suspicious. It seems like the function parameter takes in the B_p matrix instead of the full affine matrix?
</blockquote></details>

So by your convention, the affine matrix should be C_p = B_p*D_p^-1 ? (Because I call B_p as the affine matrix in the code.)

**Review by xuchen-han — CHANGES_REQUESTED** [review]
I reviewed the non-test files and will come back to this PR when the unit tests pass.

> Reviewed 9 of 12 files at r2, 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/20#-:-N5fVNrfEpESylPik0UN:b-jou6df)* status: 12 of 15 files reviewed, 8 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/Grid.h` line 53 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5fFUAb1BlvxBh7kM4O:-N5fFUAb1BlvxBh7kM4P:bteyzlr) ([raw file](https://github.com/yiminlin-tri/drake/blob/7727571f313aa1a61eabcfd2270e7e7fb4b2f143/multibody/fem/mpm-dev/Grid.h#L53)):*
> ```objc
>         double sum_mass;
>         Vector3<double> sum_momentum;
>         Vector3<double> sum_angular_momentum;
> ```

nit, we should probably mention that this is the angular momentum about the origin in the world frame.
___
*[`multibody/fem/mpm-dev/Grid.cc` line 193 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5fF3SG4OHVFijryngy:-N5fF3SG4OHVFijryngz:b-kkbzym) ([raw file](https://github.com/yiminlin-tri/drake/blob/7727571f313aa1a61eabcfd2270e7e7fb4b2f143/multibody/fem/mpm-dev/Grid.cc#L193)):*
> ```cpp
>                 i < bottom_corner_(0)+num_gridpt_1D_(0); ++i) {
>         double mi = get_mass(i, j, k);
>         // std::cout << mi << std::endl;
> ```

nit residue of debugging session.
___
*[`multibody/fem/mpm-dev/MathUtils.h` line 16 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5fUd7v5-d9UtS3bsEm:-N5fUd7v5-d9UtS3bsEn:bpaau1r) ([raw file](https://github.com/yiminlin-tri/drake/blob/7727571f313aa1a61eabcfd2270e7e7fb4b2f143/multibody/fem/mpm-dev/MathUtils.h#L16)):*
> ```objc
> 
>     // Calculate A:ε
>     static Vector3<double> APermutation(const Matrix3<double>& A);
> ```

If this class is only going to contain static functions, consider making them free functions instead.

optional, probably a better name would be `ContractionWithLeviCivita`?
___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 115 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5bJfHY0rHp519ObT2D:-N5fC4398PToIOIsJs_D:b-kufkx2) ([raw file](https://github.com/yiminlin-tri/drake/blob/0061e1617d06c00f41cd926274a778f79d0e35a2/multibody/fem/mpm-dev/MPMTransfer.h#L115)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

I passed in velocity because I can reuse m_ip = m_p * w_ip once, so possibly saving one operation...
</blockquote></details>

I see, thanks.
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 40 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5bKEYM6US6tcYTWPU7:-N5fAje73Q3nh63pwuKT:bxorcxg) ([raw file](https://github.com/yiminlin-tri/drake/blob/0061e1617d06c00f41cd926274a778f79d0e35a2/multibody/fem/mpm-dev/MPMTransfer.cc#L40)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

So by your convention, the affine matrix should be C_p = B_p*D_p^-1 ? (Because I call B_p as the affine matrix in the code.)
</blockquote></details>

Yeah, C_p is named the affine matrix because the velocity is given by v = vp + Cp(xi-xp).
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 10 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5fUMYc3hKSHATHhLsT:-N5fUMYc3hKSHATHhLsU:b-uuevv7) ([raw file](https://github.com/yiminlin-tri/drake/blob/7727571f313aa1a61eabcfd2270e7e7fb4b2f143/multibody/fem/mpm-dev/MPMTransfer.cc#L10)):*
> ```cpp
>     SortParticles(grid, particles);
>     UpdateBasisAndGradientParticles(grid, *particles);
>     Dp_inv_ = 4.0/(grid.get_h()*grid.get_h());
> ```

nit, a comment here that this is hard coded for quadratic bspline. Ideally also add a reference to where the formula comes from.
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 239 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5fUDkg4HQ_zqQ5bxv2:-N5fUDkg4HQ_zqQ5bxv3:bf39101) ([raw file](https://github.com/yiminlin-tri/drake/blob/7727571f313aa1a61eabcfd2270e7e7fb4b2f143/multibody/fem/mpm-dev/MPMTransfer.cc#L239)):*
> ```cpp
>         double m_ip = m_p*Ni_p;
>         state_i.mass += m_ip;
>         state_i.velocity += m_ip*(v_p+B_p*Dp_inv_*(x_i-x_p));
> ```

Per f2f, we need to pass in all the grid node positions of the batch.
___
*[`multibody/fem/mpm-dev/Particles.h` line 23 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5fU61CDzMLHh9p9fT2:-N5fU61D27eHy0_VG5fh:b-2i31iy) ([raw file](https://github.com/yiminlin-tri/drake/blob/7727571f313aa1a61eabcfd2270e7e7fb4b2f143/multibody/fem/mpm-dev/Particles.h#L23)):*
> ```objc
>         double sum_mass;
>         Vector3<double> sum_momentum;
>         Vector3<double> sum_angular_momentum;
> ```

nit mention this is angular momentum about the origin in world frame.
___
*[`multibody/fem/mpm-dev/Particles.h` line 101 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5fTsjF3KEclxzMrvio:-N5fTsjGAftitY3PW4Ix:b-fgziz1) ([raw file](https://github.com/yiminlin-tri/drake/blob/7727571f313aa1a61eabcfd2270e7e7fb4b2f143/multibody/fem/mpm-dev/Particles.h#L101)):*
> ```objc
> 
>     // Return the sum of mass, momentum and angular momentum of all particles.
>     // The sum of particles' angular momentums is ∑ mp xp×vp + Bp^T:ϵ
> ```

It'd be nice to add a reference here to where the expression for the angular momentum comes from

https://www.math.ucla.edu/~jteran/papers/JST17.pdf section 5.3.1
___
*[`multibody/fem/mpm-dev/Particles.cc` line 229 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5fHVfO3akBHs9wCSKy:-N5fHVfO3akBHs9wCSKz:b2oohqn) ([raw file](https://github.com/yiminlin-tri/drake/blob/7727571f313aa1a61eabcfd2270e7e7fb4b2f143/multibody/fem/mpm-dev/Particles.cc#L229)):*
> ```cpp
>         const Vector3<double>& vp = velocities_[p];
>         const Vector3<double>& xp = positions_[p];
>         const Matrix3<double>& Bp = affine_matrices_[p];
> ```

nit we should rename affine_matrices.

**Review by yiminlin-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/20)* status: 2 of 15 files reviewed, 3 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 40 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5bKEYM6US6tcYTWPU7:-N5gBb7h7Jc52c1YgojP:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/0061e1617d06c00f41cd926274a778f79d0e35a2/multibody/fem/mpm-dev/MPMTransfer.cc#L40)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Yeah, C_p is named the affine matrix because the velocity is given by v = vp + Cp(xi-xp).
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 239 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5fUDkg4HQ_zqQ5bxv2:-N5fcEmkBCbexTYNR8r3:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/7727571f313aa1a61eabcfd2270e7e7fb4b2f143/multibody/fem/mpm-dev/MPMTransfer.cc#L239)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Per f2f, we need to pass in all the grid node positions of the batch.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/Particles.h` line 101 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5fTsjF3KEclxzMrvio:-N5fcWM7Dsb3oqvSTbMu:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/7727571f313aa1a61eabcfd2270e7e7fb4b2f143/multibody/fem/mpm-dev/Particles.h#L101)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

It'd be nice to add a reference here to where the expression for the angular momentum comes from

https://www.math.ucla.edu/~jteran/papers/JST17.pdf section 5.3.1
</blockquote></details>

Done.

**Review by xuchen-han — CHANGES_REQUESTED** [review]
:lgtm: with a few minor comments.

> Reviewed 1 of 12 files at r2, 12 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/20#-:-N5gzuMm795nzSMtaNg_:bavmcyl)* status: all files reviewed (commit messages unreviewed), 6 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/Grid.cc` line 55 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5gRke26IEX5CN_u-sG:-N5gRke26IEX5CN_u-sH:b-f3hhnk) ([raw file](https://github.com/yiminlin-tri/drake/blob/f88b00935fa26ef071abce97fe6688720aec67f4/multibody/fem/mpm-dev/Grid.cc#L55)):*
> ```cpp
> }
> 
> const Vector3<double>& Grid::get_position(int i, int j, int k) const {
> ```

nit, Just realizing here it may be more efficient to return by value `Vector3<double>(i*h, j*h, k*h)`? 
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 21 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5gx7JxDzqgGvcIfEk-:-N5gx7JxDzqgGvcIfEk0:b-dj7gxz) ([raw file](https://github.com/yiminlin-tri/drake/blob/f88b00935fa26ef071abce97fe6688720aec67f4/multibody/fem/mpm-dev/MPMTransfer.cc#L21)):*
> ```cpp
>     double mass_p, ref_volume_p;
>     // Local sum of states m_i v_i f_i on the grid points
>     std::array<GridState, 27> sum_local;
> ```

nit, now that we have `sum_grid_state`, this `sum_local` variable becomes a little confusing and it tripped me up a few times. Can we call it something else, like `local_pad`? The intuition behind that name is that each batch is a "pad", and the whole grid is made up of a bunch of these little pads.
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 253 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5gvmyv3299qnSyVQD7:-N5gvmyv3299qnSyVQD8:b5dpha6) ([raw file](https://github.com/yiminlin-tri/drake/blob/f88b00935fa26ef071abce97fe6688720aec67f4/multibody/fem/mpm-dev/MPMTransfer.cc#L253)):*
> ```cpp
>         Ni_p = bases_val_particles_[p][idx_local];
>         const Vector3<double>& x_i = batch_positions[idx_local];
>         Vector3<double>& gradNi_p  = bases_grad_particles_[p][idx_local];
> ```

nit, use a const reference instead.
___
*[`multibody/fem/mpm-dev/Particles.h` line 21 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5gy8fF1s85hms_8tDv:-N5gy8fF1s85hms_8tDw:bfxg7m5) ([raw file](https://github.com/yiminlin-tri/drake/blob/f88b00935fa26ef071abce97fe6688720aec67f4/multibody/fem/mpm-dev/Particles.h#L21)):*
> ```objc
>     // Store the sum of mass, momentum and angular momentum of the grid
>     // The angular momentum is about the origin in the world frame
>     struct ParticlesSumState {
> ```

I just realized `ParticlesSumState` and `GridSumState` have no reason to be two distinct classes. They contain the exact same data members. Can we combine them and simply call it `TotalMassAndMomentum`?
___
*[`multibody/fem/mpm-dev/Particles.h` line 60 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5gvwPi7HljdrVHYrnJ:-N5gvwPi7HljdrVHYrnK:bz7fp9p) ([raw file](https://github.com/yiminlin-tri/drake/blob/f88b00935fa26ef071abce97fe6688720aec67f4/multibody/fem/mpm-dev/Particles.h#L60)):*
> ```objc
>     void set_kirchhoff_stress(int index,
>                               const Matrix3<double>& kirchhoff_stress);
>     void set_B_matrix(int index, const Matrix3<double>& B_matrix);
> ```

nit, document what B is. Ditto for the getter and `AddParticle` below.
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 533 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5gykA-6RXXrJF8ySMJ:-N5gygsOBQa2UwmrM1_u:b-1x23w) ([raw file](https://github.com/yiminlin-tri/drake/blob/f88b00935fa26ef071abce97fe6688720aec67f4/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L533)):*
> ```cpp
>             dummy_momentum = dummy_mass*dummy_velocity;
>             dummy_tau = pc*Matrix3<double>::Identity();
>             dummy_B = Matrix3<double>::Zero();
> ```

nit, can we use a nonzero B for testing throughout?

**Review by yiminlin-tri — COMMENTED** [review]
Fixed. Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/20#-:-N5hDNW4EqVAYAc8jxh1:b-d5q2i1)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/Particles.h` line 21 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/20#-N5gy8fF1s85hms_8tDv:-N5hDMor-JPqPaEQPsjc:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/f88b00935fa26ef071abce97fe6688720aec67f4/multibody/fem/mpm-dev/Particles.h#L21)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I just realized `ParticlesSumState` and `GridSumState` have no reason to be two distinct classes. They contain the exact same data members. Can we combine them and simply call it `TotalMassAndMomentum`?
</blockquote></details>

Done.

**Review by xuchen-han — APPROVED** [review]
> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)

**Pull request merged**
